package DisenoDePatrones.Vista.Layouts.Auths;

import DisenoDePatrones.Vista.Layouts.Window.WindowForm;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Alex
 */
public class AuthForm extends javax.swing.JPanel {
    
    public AuthForm(WindowForm window) {
        initComponents();
        this.contentDragged1.initDragSystem(window);
    }
    
    public JPanel getContent() {
        return this.content;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentDragged1 = new DisenoDePatrones.Vista.Components.ContentDragged();
        content = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentDragged1.setTitleBar("Login");
        add(contentDragged1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        content.setLayout(new java.awt.CardLayout());
        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 660));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private DisenoDePatrones.Vista.Components.ContentDragged contentDragged1;
    // End of variables declaration//GEN-END:variables
}
