package DisenoDePatrones.Vista.Layouts.Auths;

import DisenoDePatrones.Vista.Components.PanelRound;
import DisenoDePatrones.Vista.Window;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Alex
 */
public class AuthForm extends javax.swing.JPanel {
    public enum Modos {
        CIUDADANO,
        FUERZA_ORDEN,
        AGENTE_PUBLICO
    }
    
    private Modos currentMode;
    
    private JLabel currentLabel;
    private PanelRound currentPanel;

    public AuthForm(Window window) {
        initComponents();
        this.contentDragged1.initDragSystem(window);
        this.SwitchModeAccess(this.btnModeCiudadano, this.jLabel1);
    }
    
    public Modos getModeAccess() {
        return this.currentMode;
    }
    
    public JPanel getContent() {
        return this.content;
    }
    
    private void SwitchModeAccess(PanelRound pn, JLabel label) {
        if (this.currentPanel != null) {
            this.currentPanel.setBackground(Color.WHITE);
            this.currentLabel.setForeground(new Color(64, 76, 102));
        }
        
        this.currentPanel = pn;
        this.currentLabel = label;
        
        this.currentPanel.setBackground(new Color(64, 76, 102));
        this.currentLabel.setForeground(Color.WHITE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentDragged1 = new DisenoDePatrones.Vista.Components.ContentDragged();
        jPanel1 = new javax.swing.JPanel();
        btnModeCiudadano = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        btnModeFOrden = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        btnModeAPublico = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentDragged1.setTitleBar("Login");
        add(contentDragged1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        btnModeCiudadano.setBackground(new java.awt.Color(255, 255, 255));
        btnModeCiudadano.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnModeCiudadano.setPreferredSize(new java.awt.Dimension(200, 30));
        btnModeCiudadano.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 76, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CIUDADANO");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        btnModeCiudadano.add(jLabel1, "card2");

        jPanel1.add(btnModeCiudadano);

        btnModeFOrden.setBackground(new java.awt.Color(255, 255, 255));
        btnModeFOrden.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnModeFOrden.setPreferredSize(new java.awt.Dimension(200, 30));
        btnModeFOrden.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 76, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("FUERZA DEL ORDEN");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        btnModeFOrden.add(jLabel2, "card2");

        jPanel1.add(btnModeFOrden);

        btnModeAPublico.setBackground(new java.awt.Color(255, 255, 255));
        btnModeAPublico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnModeAPublico.setPreferredSize(new java.awt.Dimension(200, 30));
        btnModeAPublico.setLayout(new java.awt.CardLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 76, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("AGENTE PUBLICO");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        btnModeAPublico.add(jLabel3, "card2");

        jPanel1.add(btnModeAPublico);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 800, -1));

        content.setOpaque(false);
        content.setPreferredSize(new java.awt.Dimension(800, 570));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.currentMode = Modos.CIUDADANO;
        this.SwitchModeAccess(this.btnModeCiudadano, this.jLabel1);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.currentMode = Modos.FUERZA_ORDEN;
        this.SwitchModeAccess(this.btnModeFOrden, this.jLabel2);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.currentMode = Modos.AGENTE_PUBLICO;
        this.SwitchModeAccess(this.btnModeAPublico, this.jLabel3);
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DisenoDePatrones.Vista.Components.PanelRound btnModeAPublico;
    private DisenoDePatrones.Vista.Components.PanelRound btnModeCiudadano;
    private DisenoDePatrones.Vista.Components.PanelRound btnModeFOrden;
    private javax.swing.JPanel content;
    private DisenoDePatrones.Vista.Components.ContentDragged contentDragged1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
