/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.Auths;

import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Alex
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form InicioSesion
     */
    public Login() {
        initComponents();
    }
    
    public JButton GetButtonAcceder() {
        return this.btnAcceder;
    }
    
    public JLabel GetChangeToRegister() {
        return this.btnRegister;
    }
    
    public HashMap<String, String> GetData() {
        HashMap<String, String> data = new HashMap<>();
        
        data.put("CampoDNI", this.tbDni.getText());
        data.put("CampoPassword", this.tbPassword.getText());
        
        return data;
    }
    
    public void SetData(HashMap<String, String> data) {      
        this.tbDni.setText(data.get("CampoDNI"));
        this.tbPassword.setText(data.get("CampoPassword"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnContent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelRound2 = new DisenoDePatrones.Vista.Components.PanelRound();
        btnRegister = new javax.swing.JLabel();
        panelRound1 = new DisenoDePatrones.Vista.Components.PanelRound();
        btnAcceder = new javax.swing.JButton();
        tbDni = new DisenoDePatrones.Vista.Components.TextField();
        tbPassword = new DisenoDePatrones.Vista.Components.TextField();
        jPanel3 = new javax.swing.JPanel();
        pnContent1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnContent.setBackground(new java.awt.Color(255, 255, 255));
        pnContent.setPreferredSize(new java.awt.Dimension(390, 570));
        pnContent.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 76, 102));
        jLabel1.setText("<html><body style='width: 100%;text-align: center;'>INICIAR SESION</body></html>");
        jLabel1.setPreferredSize(new java.awt.Dimension(335, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 40;
        pnContent.add(jLabel1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 76, 102));
        jLabel3.setText("<html><body style='width: 100%;'>Descubre cómo la plataforma de Gestión Ciudadana te permite participar activamente.</body></html>");
        jLabel3.setPreferredSize(new java.awt.Dimension(335, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 10;
        pnContent.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(69, 132, 255));
        jLabel4.setText("Documento de Identidad");
        jLabel4.setPreferredSize(new java.awt.Dimension(335, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        pnContent.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(69, 132, 255));
        jLabel5.setText("Contraseña");
        jLabel5.setPreferredSize(new java.awt.Dimension(335, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        pnContent.add(jLabel5, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(331, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        pnContent.add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setToolTipText("");
        jPanel2.setPreferredSize(new java.awt.Dimension(331, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        pnContent.add(jPanel2, gridBagConstraints);

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 132, 255), 2, true));
        panelRound2.setPreferredSize(new java.awt.Dimension(331, 40));
        panelRound2.setRoundBottomLeft(4);
        panelRound2.setRoundBottomRight(4);
        panelRound2.setRoundTopLeft(4);
        panelRound2.setRoundTopRight(4);
        panelRound2.setLayout(new java.awt.CardLayout());

        btnRegister.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(69, 132, 255));
        btnRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegister.setText("REGISTARME");
        btnRegister.setPreferredSize(new java.awt.Dimension(335, 32));
        panelRound2.add(btnRegister, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 10;
        pnContent.add(panelRound2, gridBagConstraints);

        panelRound1.setBackground(new java.awt.Color(69, 132, 255));
        panelRound1.setPreferredSize(new java.awt.Dimension(331, 40));
        panelRound1.setRoundBottomLeft(5);
        panelRound1.setRoundBottomRight(5);
        panelRound1.setRoundTopLeft(5);
        panelRound1.setRoundTopRight(5);
        panelRound1.setLayout(new java.awt.CardLayout());

        btnAcceder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnAcceder.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceder.setText("ACCEDER");
        btnAcceder.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAcceder.setBorderPainted(false);
        btnAcceder.setContentAreaFilled(false);
        btnAcceder.setFocusPainted(false);
        panelRound1.add(btnAcceder, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        pnContent.add(panelRound1, gridBagConstraints);

        tbDni.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 132, 255), 2, true));
        tbDni.setDisabledTextColor(new java.awt.Color(224, 224, 224));
        tbDni.setPlaceholder("ej. 985741746");
        tbDni.setPreferredSize(new java.awt.Dimension(331, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 10;
        pnContent.add(tbDni, gridBagConstraints);

        tbPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 132, 255), 2, true));
        tbPassword.setPlaceholder("...");
        tbPassword.setPreferredSize(new java.awt.Dimension(331, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipady = 10;
        pnContent.add(tbPassword, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(331, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 9;
        pnContent.add(jPanel3, gridBagConstraints);

        add(pnContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnContent1.setBackground(new java.awt.Color(234, 245, 255));
        pnContent1.setForeground(new java.awt.Color(64, 76, 102));
        pnContent1.setPreferredSize(new java.awt.Dimension(410, 570));
        pnContent1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 76, 102));
        jLabel2.setText("<html><body style='width: 100%;text-align: center;'>GESTIONA TU CIUDAD, MEJORA LA CALIDAD DE VIDA.</body></html>");
        jLabel2.setPreferredSize(new java.awt.Dimension(335, 32));
        pnContent1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 335, 96));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/image1.png"))); // NOI18N
        pnContent1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 640, 448));

        add(pnContent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound1;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound2;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnContent1;
    private DisenoDePatrones.Vista.Components.TextField tbDni;
    private DisenoDePatrones.Vista.Components.TextField tbPassword;
    // End of variables declaration//GEN-END:variables
}
