/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.Auths;

import java.util.HashMap;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Alex
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form InicioSesion
     */
    public Login() {
        initComponents();
    }
    
    public JButton GetButtonAcceder() {
        return this.btnAcceder;
    }
    
    public JButton GetChangeToRegister() {
        return this.btnRegister;
    }
    
    public ButtonGroup GetButtonGroup() {
        return this.typeCiudadano;
    }
    
    public HashMap<String, String> GetData() {
        HashMap<String, String> data = new HashMap<>();
        
        data.put("CampoDNI", this.tbDni.getText());
        data.put("CampoPassword", this.tbPassword.getText());
        
        return data;
    }
    
    public void SetData(HashMap<String, String> data) {      
        this.tbDni.setText(data.get("CampoDNI"));
        this.tbPassword.setText(data.get("CampoPassword"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeCiudadano = new javax.swing.ButtonGroup();
        pnContent = new javax.swing.JPanel();
        pnContent1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tbPassword = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        jLabel8 = new javax.swing.JLabel();
        tbDni = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        jLabel3 = new javax.swing.JLabel();
        radioAgentePublico = new javax.swing.JRadioButton();
        radioCiudadano = new javax.swing.JRadioButton();
        radioFDelOrden = new javax.swing.JRadioButton();
        btnRegister = new DisenoDePatrones.Vista.Components.ImageButton();
        btnAcceder = new DisenoDePatrones.Vista.Components.ImageButton();
        image = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnContent.setBackground(new java.awt.Color(255, 255, 255));
        pnContent.setPreferredSize(new java.awt.Dimension(400, 660));
        pnContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnContent1.setBackground(new java.awt.Color(255, 255, 255));
        pnContent1.setPreferredSize(new java.awt.Dimension(400, 660));
        pnContent1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(69, 132, 255));
        jLabel5.setText("Contraseña");
        jLabel5.setPreferredSize(new java.awt.Dimension(340, 20));
        pnContent1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(64, 76, 102));
        jLabel6.setText("INICIAR SESION");
        pnContent1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(64, 76, 102));
        jLabel7.setText("<html><body style='width:100%;'>Descubre cómo la plataforma de Gestión Ciudadana te permite participar activamente.</body></html>");
        jLabel7.setPreferredSize(new java.awt.Dimension(340, 42));
        pnContent1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 102, -1, -1));

        tbPassword.setFontFamily(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbPassword.setGap(new java.awt.Point(5, 0));
        tbPassword.setPlaceholder("...");
        tbPassword.setPlaceholderForeground(new java.awt.Color(153, 153, 153));
        tbPassword.setText("");
        tbPassword.setTextForeground(new java.awt.Color(64, 76, 102));
        tbPassword.setBackgroundColor(new java.awt.Color(255, 255, 255));
        tbPassword.setBorderColor(new java.awt.Color(69, 132, 255));
        tbPassword.setBorderThickness(1);
        tbPassword.setCornerRadius(4);
        tbPassword.setPreferredSize(new java.awt.Dimension(340, 27));
        pnContent1.add(tbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 244, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(69, 132, 255));
        jLabel8.setText("Documento de Identidad");
        jLabel8.setPreferredSize(new java.awt.Dimension(340, 20));
        pnContent1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        tbDni.setFontFamily(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbDni.setGap(new java.awt.Point(5, 0));
        tbDni.setPlaceholder("ej. Juan Pablo");
        tbDni.setPlaceholderForeground(new java.awt.Color(153, 153, 153));
        tbDni.setText("");
        tbDni.setTextForeground(new java.awt.Color(64, 76, 102));
        tbDni.setBackgroundColor(new java.awt.Color(255, 255, 255));
        tbDni.setBorderColor(new java.awt.Color(69, 132, 255));
        tbDni.setBorderThickness(1);
        tbDni.setCornerRadius(4);
        tbDni.setPreferredSize(new java.awt.Dimension(340, 27));
        pnContent1.add(tbDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 183, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 76, 102));
        jLabel3.setText("Tipo de Usuario");
        jLabel3.setPreferredSize(new java.awt.Dimension(340, 20));
        pnContent1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 286, -1, -1));

        typeCiudadano.add(radioAgentePublico);
        radioAgentePublico.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        radioAgentePublico.setForeground(new java.awt.Color(64, 76, 102));
        radioAgentePublico.setText("AGENTE PUBLICO");
        pnContent1.add(radioAgentePublico, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        typeCiudadano.add(radioCiudadano);
        radioCiudadano.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        radioCiudadano.setForeground(new java.awt.Color(64, 76, 102));
        radioCiudadano.setSelected(true);
        radioCiudadano.setText("CIUDADANO");
        pnContent1.add(radioCiudadano, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        typeCiudadano.add(radioFDelOrden);
        radioFDelOrden.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        radioFDelOrden.setForeground(new java.awt.Color(64, 76, 102));
        radioFDelOrden.setText("FUERZA DEL ORDEN");
        pnContent1.add(radioFDelOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        btnRegister.setBorder(null);
        btnRegister.setText("");
        btnRegister.setImageName("Login/Action-1.png");
        pnContent1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 574, -1, -1));

        btnAcceder.setBorder(null);
        btnAcceder.setText("");
        btnAcceder.setImageName("Login/Action.png");
        pnContent1.add(btnAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 528, -1, -1));

        pnContent.add(pnContent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(pnContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/AuthBackgroundImage.png"))); // NOI18N
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DisenoDePatrones.Vista.Components.ImageButton btnAcceder;
    private DisenoDePatrones.Vista.Components.ImageButton btnRegister;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnContent1;
    private javax.swing.JRadioButton radioAgentePublico;
    private javax.swing.JRadioButton radioCiudadano;
    private javax.swing.JRadioButton radioFDelOrden;
    private DisenoDePatrones.Vista.Components.TextBoxElement.TextBox tbDni;
    private DisenoDePatrones.Vista.Components.TextBoxElement.TextBox tbPassword;
    private javax.swing.ButtonGroup typeCiudadano;
    // End of variables declaration//GEN-END:variables
}
