/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.Auths;

import java.util.HashMap;
import javax.swing.JLabel;

/**
 *
 * @author Alex
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form InicioSesion
     */
    public Register() {
        initComponents();
    }

     public JLabel GetButtonAcceder() {
        return this.btnAcceder;
    }
    
    public JLabel GetChangeToLogin() {
        return this.btnLogin;
    }
    
    public HashMap<String, String> GetData() {
        HashMap<String, String> data = new HashMap<>();
        
        data.put("CampoDNI", this.tbDNI.getText());
        data.put("CampoNombres", this.tbNombres.getText());
        data.put("CampoApellidos", this.tbApellidos.getText());
        data.put("CampoCorreo", this.tbCorreo.getText());
        data.put("CampoPassword", this.tbPassword.getText());
        data.put("CampoRepeatPassword", this.tbPasswordRep.getText());
        
        return data;
    }
    
    public void SetData(HashMap<String, String> data) {      
        this.tbDNI.setText(data.get("CampoDNI"));
        this.tbNombres.setText(data.get("CampoNombres"));
        this.tbApellidos.setText(data.get("CampoApellidos"));
        this.tbCorreo.setText(data.get("CampoCorreo"));
        this.tbPassword.setText(data.get("CampoPassword"));      
        this.tbPasswordRep.setText(data.get("CampoRepeatPassword"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnContent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tbDNI = new DisenoDePatrones.Vista.Components.TextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tbNombres = new DisenoDePatrones.Vista.Components.TextField();
        jLabel9 = new javax.swing.JLabel();
        tbApellidos = new DisenoDePatrones.Vista.Components.TextField();
        jLabel10 = new javax.swing.JLabel();
        tbCorreo = new DisenoDePatrones.Vista.Components.TextField();
        jLabel11 = new javax.swing.JLabel();
        tbPassword = new DisenoDePatrones.Vista.Components.TextField();
        jLabel12 = new javax.swing.JLabel();
        tbPasswordRep = new DisenoDePatrones.Vista.Components.TextField();
        panelRound1 = new DisenoDePatrones.Vista.Components.PanelRound();
        btnAcceder = new javax.swing.JLabel();
        panelRound2 = new DisenoDePatrones.Vista.Components.PanelRound();
        btnLogin = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnContent1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnContent.setBackground(new java.awt.Color(255, 255, 255));
        pnContent.setPreferredSize(new java.awt.Dimension(390, 570));
        pnContent.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 76, 102));
        jLabel1.setText("REGISTRARSE");
        jLabel1.setPreferredSize(new java.awt.Dimension(335, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 10;
        pnContent.add(jLabel1, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 76, 102));
        jLabel3.setText("<html><body style='width: 100%;'>Descubre cómo la plataforma de Gestión Ciudadana te permite participar activamente.</body></html>");
        jLabel3.setPreferredSize(new java.awt.Dimension(335, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 10;
        pnContent.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(69, 132, 255));
        jLabel4.setText("Documento de Identidad");
        jLabel4.setPreferredSize(new java.awt.Dimension(335, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        pnContent.add(jLabel4, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(331, 15));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        pnContent.add(jPanel1, gridBagConstraints);

        tbDNI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 132, 255), 2, true));
        tbDNI.setDisabledTextColor(new java.awt.Color(224, 224, 224));
        tbDNI.setPlaceholder("ej. 985741746");
        tbDNI.setPreferredSize(new java.awt.Dimension(331, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        pnContent.add(tbDNI, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(331, 60));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(69, 132, 255));
        jLabel8.setText("Nombres");
        jLabel8.setPreferredSize(new java.awt.Dimension(335, 32));
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, -1));

        tbNombres.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 132, 255), 2, true));
        tbNombres.setDisabledTextColor(new java.awt.Color(224, 224, 224));
        tbNombres.setPlaceholder("ej. Juan Pablo");
        tbNombres.setPreferredSize(new java.awt.Dimension(331, 30));
        jPanel4.add(tbNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 160, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(69, 132, 255));
        jLabel9.setText("Apellidos");
        jLabel9.setPreferredSize(new java.awt.Dimension(335, 32));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 160, -1));

        tbApellidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 132, 255), 2, true));
        tbApellidos.setDisabledTextColor(new java.awt.Color(224, 224, 224));
        tbApellidos.setPlaceholder("ej. Segundo");
        tbApellidos.setPreferredSize(new java.awt.Dimension(331, 30));
        jPanel4.add(tbApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 160, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        pnContent.add(jPanel4, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(69, 132, 255));
        jLabel10.setText("Correo Electronico");
        jLabel10.setPreferredSize(new java.awt.Dimension(335, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        pnContent.add(jLabel10, gridBagConstraints);

        tbCorreo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 132, 255), 2, true));
        tbCorreo.setDisabledTextColor(new java.awt.Color(224, 224, 224));
        tbCorreo.setPlaceholder("ej. juanpablo@gmail.com");
        tbCorreo.setPreferredSize(new java.awt.Dimension(331, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        pnContent.add(tbCorreo, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(69, 132, 255));
        jLabel11.setText("Contraseña");
        jLabel11.setPreferredSize(new java.awt.Dimension(335, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        pnContent.add(jLabel11, gridBagConstraints);

        tbPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 132, 255), 2, true));
        tbPassword.setDisabledTextColor(new java.awt.Color(224, 224, 224));
        tbPassword.setPlaceholder("...");
        tbPassword.setPreferredSize(new java.awt.Dimension(331, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 9;
        pnContent.add(tbPassword, gridBagConstraints);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(69, 132, 255));
        jLabel12.setText("Repetir Contraseña");
        jLabel12.setPreferredSize(new java.awt.Dimension(335, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        pnContent.add(jLabel12, gridBagConstraints);

        tbPasswordRep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 132, 255), 2, true));
        tbPasswordRep.setDisabledTextColor(new java.awt.Color(224, 224, 224));
        tbPasswordRep.setPlaceholder("...");
        tbPasswordRep.setPreferredSize(new java.awt.Dimension(331, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 11;
        pnContent.add(tbPasswordRep, gridBagConstraints);

        panelRound1.setBackground(new java.awt.Color(69, 132, 255));
        panelRound1.setPreferredSize(new java.awt.Dimension(331, 40));
        panelRound1.setRoundBottomLeft(4);
        panelRound1.setRoundBottomRight(4);
        panelRound1.setRoundTopLeft(4);
        panelRound1.setRoundTopRight(4);
        panelRound1.setLayout(new java.awt.CardLayout());

        btnAcceder.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        btnAcceder.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAcceder.setText("CONTINUAR");
        btnAcceder.setPreferredSize(new java.awt.Dimension(335, 32));
        panelRound1.add(btnAcceder, "card2");
        btnAcceder.getAccessibleContext().setAccessibleDescription("");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 13;
        pnContent.add(panelRound1, gridBagConstraints);

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(69, 132, 255), 2, true));
        panelRound2.setPreferredSize(new java.awt.Dimension(331, 40));
        panelRound2.setRoundBottomLeft(4);
        panelRound2.setRoundBottomRight(4);
        panelRound2.setRoundTopLeft(4);
        panelRound2.setRoundTopRight(4);
        panelRound2.setLayout(new java.awt.CardLayout());

        btnLogin.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(69, 132, 255));
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin.setText("INICIAR SESION");
        btnLogin.setPreferredSize(new java.awt.Dimension(335, 32));
        panelRound2.add(btnLogin, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 15;
        pnContent.add(panelRound2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(331, 4));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 14;
        pnContent.add(jPanel3, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(331, 15));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 12;
        pnContent.add(jPanel2, gridBagConstraints);

        add(pnContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnContent1.setBackground(new java.awt.Color(234, 245, 255));
        pnContent1.setForeground(new java.awt.Color(64, 76, 102));
        pnContent1.setPreferredSize(new java.awt.Dimension(410, 570));
        pnContent1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 76, 102));
        jLabel2.setText("<html><body style='width: 100%;text-align: center;'>GESTIONA TU CIUDAD, MEJORA LA CALIDAD DE VIDA.</body></html>");
        jLabel2.setPreferredSize(new java.awt.Dimension(335, 32));
        pnContent1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 335, 96));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/image1.png"))); // NOI18N
        pnContent1.add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 640, 448));

        add(pnContent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAcceder;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound1;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound2;
    private javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnContent1;
    private DisenoDePatrones.Vista.Components.TextField tbApellidos;
    private DisenoDePatrones.Vista.Components.TextField tbCorreo;
    private DisenoDePatrones.Vista.Components.TextField tbDNI;
    private DisenoDePatrones.Vista.Components.TextField tbNombres;
    private DisenoDePatrones.Vista.Components.TextField tbPassword;
    private DisenoDePatrones.Vista.Components.TextField tbPasswordRep;
    // End of variables declaration//GEN-END:variables
}
