/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.Auths;

import java.util.HashMap;
import javax.swing.ButtonGroup;
import javax.swing.JButton;

/**
 *
 * @author Alex
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form InicioSesion
     */
    public Register() {
        initComponents();
    }

     public JButton GetButtonAcceder() {
        return this.btnRegister;
    }
    
    public JButton GetChangeToLogin() {
        return this.btnLogin;
    }
    
    public ButtonGroup GetButtonGroup() {
        return this.typeCiudadano;
    }
    
    public HashMap<String, String> GetData() {
        HashMap<String, String> data = new HashMap<>();
        
        data.put("CampoDNI", this.tbNombres.getText());
        data.put("CampoNombres", this.tbNombres.getText());
        data.put("CampoApellidos", this.tbApellidos.getText());
        data.put("CampoCorreo", this.tbCorreo.getText());
        data.put("CampoPassword", this.tbPassword.getText());
        data.put("CampoRepeatPassword", this.tbPasswordRep.getText());
        
        return data;
    }
    
    public void SetData(HashMap<String, String> data) {      
        this.tbNombres.setText(data.get("CampoDNI"));
        this.tbApellidos.setText(data.get("CampoNombres"));
        this.tbApellidos.setText(data.get("CampoApellidos"));
        this.tbCorreo.setText(data.get("CampoCorreo"));
        this.tbPassword.setText(data.get("CampoPassword"));      
        this.tbPasswordRep.setText(data.get("CampoRepeatPassword"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeCiudadano = new javax.swing.ButtonGroup();
        pnContent = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tbNombres = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        jLabel9 = new javax.swing.JLabel();
        tbDni1 = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        jLabel10 = new javax.swing.JLabel();
        tbApellidos = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        tbCorreo = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tbPassword = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        tbPasswordRep = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radioCiudadano = new javax.swing.JRadioButton();
        radioFDelOrden = new javax.swing.JRadioButton();
        radioAgentePublico = new javax.swing.JRadioButton();
        btnLogin = new DisenoDePatrones.Vista.Components.ImageButton();
        btnRegister = new DisenoDePatrones.Vista.Components.ImageButton();
        image = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnContent.setBackground(new java.awt.Color(255, 255, 255));
        pnContent.setPreferredSize(new java.awt.Dimension(400, 660));
        pnContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(64, 76, 102));
        jLabel6.setText("REGISTRARSE");
        pnContent.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(64, 76, 102));
        jLabel7.setText("<html><body style='width:100%;'>Descubre cómo la plataforma de Gestión Ciudadana te permite participar activamente.</body></html>");
        jLabel7.setPreferredSize(new java.awt.Dimension(340, 42));
        pnContent.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 102, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(69, 132, 255));
        jLabel8.setText("Nombres");
        jLabel8.setPreferredSize(new java.awt.Dimension(165, 20));
        pnContent.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 218, -1, -1));

        tbNombres.setFontFamily(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbNombres.setGap(new java.awt.Point(5, 0));
        tbNombres.setPlaceholder("ej. Juan Pedro");
        tbNombres.setPlaceholderForeground(new java.awt.Color(153, 153, 153));
        tbNombres.setText("");
        tbNombres.setTextForeground(new java.awt.Color(64, 76, 102));
        tbNombres.setBackgroundColor(new java.awt.Color(255, 255, 255));
        tbNombres.setBorderColor(new java.awt.Color(69, 132, 255));
        tbNombres.setBorderThickness(1);
        tbNombres.setCornerRadius(4);
        tbNombres.setPreferredSize(new java.awt.Dimension(165, 27));
        pnContent.add(tbNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(69, 132, 255));
        jLabel9.setText("Documento de Identidad");
        jLabel9.setPreferredSize(new java.awt.Dimension(340, 20));
        pnContent.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 159, -1, -1));

        tbDni1.setFontFamily(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbDni1.setGap(new java.awt.Point(5, 0));
        tbDni1.setPlaceholder("ej. 12345678");
        tbDni1.setPlaceholderForeground(new java.awt.Color(153, 153, 153));
        tbDni1.setText("");
        tbDni1.setTextForeground(new java.awt.Color(64, 76, 102));
        tbDni1.setBackgroundColor(new java.awt.Color(255, 255, 255));
        tbDni1.setBorderColor(new java.awt.Color(69, 132, 255));
        tbDni1.setBorderThickness(1);
        tbDni1.setCornerRadius(4);
        tbDni1.setPreferredSize(new java.awt.Dimension(340, 27));
        pnContent.add(tbDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 181, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(69, 132, 255));
        jLabel10.setText("Apellidos");
        jLabel10.setPreferredSize(new java.awt.Dimension(165, 20));
        pnContent.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 218, -1, -1));

        tbApellidos.setFontFamily(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbApellidos.setGap(new java.awt.Point(5, 0));
        tbApellidos.setPlaceholder("ej. Segundo");
        tbApellidos.setPlaceholderForeground(new java.awt.Color(153, 153, 153));
        tbApellidos.setText("");
        tbApellidos.setTextForeground(new java.awt.Color(64, 76, 102));
        tbApellidos.setBackgroundColor(new java.awt.Color(255, 255, 255));
        tbApellidos.setBorderColor(new java.awt.Color(69, 132, 255));
        tbApellidos.setBorderThickness(1);
        tbApellidos.setCornerRadius(4);
        tbApellidos.setPreferredSize(new java.awt.Dimension(165, 27));
        pnContent.add(tbApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 240, -1, -1));

        tbCorreo.setFontFamily(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbCorreo.setGap(new java.awt.Point(5, 0));
        tbCorreo.setPlaceholder("ej. juanpablo@dominio.com");
        tbCorreo.setPlaceholderForeground(new java.awt.Color(153, 153, 153));
        tbCorreo.setText("");
        tbCorreo.setTextForeground(new java.awt.Color(64, 76, 102));
        tbCorreo.setBackgroundColor(new java.awt.Color(255, 255, 255));
        tbCorreo.setBorderColor(new java.awt.Color(69, 132, 255));
        tbCorreo.setBorderThickness(1);
        tbCorreo.setCornerRadius(4);
        tbCorreo.setPreferredSize(new java.awt.Dimension(340, 27));
        pnContent.add(tbCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 299, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(69, 132, 255));
        jLabel11.setText("Correo Electrónico");
        jLabel11.setPreferredSize(new java.awt.Dimension(340, 20));
        pnContent.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 277, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(69, 132, 255));
        jLabel12.setText("Contraseña");
        jLabel12.setPreferredSize(new java.awt.Dimension(340, 20));
        pnContent.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 336, -1, -1));

        tbPassword.setFontFamily(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbPassword.setGap(new java.awt.Point(5, 0));
        tbPassword.setPlaceholder("...");
        tbPassword.setPlaceholderForeground(new java.awt.Color(153, 153, 153));
        tbPassword.setText("");
        tbPassword.setTextForeground(new java.awt.Color(64, 76, 102));
        tbPassword.setBackgroundColor(new java.awt.Color(255, 255, 255));
        tbPassword.setBorderColor(new java.awt.Color(69, 132, 255));
        tbPassword.setBorderThickness(1);
        tbPassword.setCornerRadius(4);
        tbPassword.setPreferredSize(new java.awt.Dimension(340, 27));
        pnContent.add(tbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 358, -1, -1));

        tbPasswordRep.setFontFamily(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbPasswordRep.setGap(new java.awt.Point(5, 0));
        tbPasswordRep.setPlaceholder("...");
        tbPasswordRep.setPlaceholderForeground(new java.awt.Color(153, 153, 153));
        tbPasswordRep.setText("");
        tbPasswordRep.setTextForeground(new java.awt.Color(64, 76, 102));
        tbPasswordRep.setBackgroundColor(new java.awt.Color(255, 255, 255));
        tbPasswordRep.setBorderColor(new java.awt.Color(69, 132, 255));
        tbPasswordRep.setBorderThickness(1);
        tbPasswordRep.setCornerRadius(4);
        tbPasswordRep.setPreferredSize(new java.awt.Dimension(340, 27));
        pnContent.add(tbPasswordRep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 417, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(69, 132, 255));
        jLabel13.setText("Repetir Contraseña");
        jLabel13.setPreferredSize(new java.awt.Dimension(340, 20));
        pnContent.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 395, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 76, 102));
        jLabel3.setText("Tipo de Usuario");
        jLabel3.setPreferredSize(new java.awt.Dimension(340, 20));
        pnContent.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 459, -1, -1));

        typeCiudadano.add(radioCiudadano);
        radioCiudadano.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        radioCiudadano.setForeground(new java.awt.Color(64, 76, 102));
        radioCiudadano.setSelected(true);
        radioCiudadano.setText("CIUDADANO");
        pnContent.add(radioCiudadano, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        typeCiudadano.add(radioFDelOrden);
        radioFDelOrden.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        radioFDelOrden.setForeground(new java.awt.Color(64, 76, 102));
        radioFDelOrden.setText("FUERZA DEL ORDEN");
        pnContent.add(radioFDelOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        typeCiudadano.add(radioAgentePublico);
        radioAgentePublico.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        radioAgentePublico.setForeground(new java.awt.Color(64, 76, 102));
        radioAgentePublico.setText("AGENTE PUBLICO");
        pnContent.add(radioAgentePublico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        btnLogin.setBorder(null);
        btnLogin.setText("");
        btnLogin.setImageName("Register/Action-1.png");
        pnContent.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 574, -1, -1));

        btnRegister.setBorder(null);
        btnRegister.setText("");
        btnRegister.setImageName("Register/Action.png");
        pnContent.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 528, -1, -1));

        add(pnContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/AuthBackgroundImage.png"))); // NOI18N
        add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DisenoDePatrones.Vista.Components.ImageButton btnLogin;
    private DisenoDePatrones.Vista.Components.ImageButton btnRegister;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnContent;
    private javax.swing.JRadioButton radioAgentePublico;
    private javax.swing.JRadioButton radioCiudadano;
    private javax.swing.JRadioButton radioFDelOrden;
    private DisenoDePatrones.Vista.Components.TextBoxElement.TextBox tbApellidos;
    private DisenoDePatrones.Vista.Components.TextBoxElement.TextBox tbCorreo;
    private DisenoDePatrones.Vista.Components.TextBoxElement.TextBox tbDni1;
    private DisenoDePatrones.Vista.Components.TextBoxElement.TextBox tbNombres;
    private DisenoDePatrones.Vista.Components.TextBoxElement.TextBox tbPassword;
    private DisenoDePatrones.Vista.Components.TextBoxElement.TextBox tbPasswordRep;
    private javax.swing.ButtonGroup typeCiudadano;
    // End of variables declaration//GEN-END:variables
}
