/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Components;

import javax.swing.JButton;

/**
 *
 * @author Alex
 */
public class CardFile extends javax.swing.JPanel {

    /**
     * Creates new form CardFile
     */
    public CardFile() {
        initComponents();
    }

    public void setFileName(String fileName) {
        this.jLabel3.setText("<html><body style='width:100%; text-align: center;'>" + fileName + "</body></html>");
    }

    public String getFileName() {
        return this.jLabel3.getText();
    }

    public void setCreationDate(String date) {
        this.lbTextDate.setText(date);
    }

    public String getCreationDate() {
        return this.lbTextDate.getText();
    }

    public void setFileSize(String size) {
        this.btnSizeFile.setText(size);
    }

    public String getFileSize() {
        return this.btnSizeFile.getText();
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public JButton getBtnDownload() {
        return btnDownload;
    }

    public void setFileType(String fileName) {
        String imagePath = "CardFiles/";
        String extension = "";

        int dotIndex = fileName.lastIndexOf('.');
        if (dotIndex > 0 && dotIndex < fileName.length() - 1) {
            extension = fileName.substring(dotIndex + 1).toLowerCase();
        }

        switch (extension) {
            case "pdf" -> imagePath += "CardPDF.png";
            case "xlsx", "xls" -> imagePath += "CardExcel.png";
            case "pptx", "ppt" -> imagePath += "CardPPT.png";
            case "docx", "doc" -> imagePath += "CardWord.png";
            case "txt" -> imagePath += "CardTodo.png";
            default -> imagePath += "CardTodo.png";
        }
        
        pictureBox1.setImage(imagePath);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureBox1 = new DisenoDePatrones.Vista.Components.PictureBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbTextDate = new javax.swing.JLabel();
        btnSizeFile = new javax.swing.JLabel();
        btnDelete = new DisenoDePatrones.Vista.Components.ImageButton();
        btnDownload = new DisenoDePatrones.Vista.Components.ImageButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        pictureBox1.setImage("CardFiles/CardPDF.png");
        pictureBox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 76, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Creación");
        pictureBox1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 80, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 76, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("<html><body style='width:100%; text-align: center;'>FileName</body></html>");
        pictureBox1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 115, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(64, 76, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Tamaño");
        pictureBox1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 80, -1));

        lbTextDate.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbTextDate.setForeground(new java.awt.Color(64, 76, 102));
        lbTextDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTextDate.setText("10/40/82");
        pictureBox1.add(lbTextDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 80, 20));

        btnSizeFile.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSizeFile.setForeground(new java.awt.Color(64, 76, 102));
        btnSizeFile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSizeFile.setText("174mb");
        pictureBox1.add(btnSizeFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 80, -1));

        btnDelete.setBorder(null);
        btnDelete.setText("");
        btnDelete.setImageName("Views/NavDelete.png");
        pictureBox1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 242, -1, -1));

        btnDownload.setBorder(null);
        btnDownload.setText("");
        btnDownload.setImageName("Views/NavDownload.png");
        pictureBox1.add(btnDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 202, -1, -1));

        add(pictureBox1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DisenoDePatrones.Vista.Components.ImageButton btnDelete;
    private DisenoDePatrones.Vista.Components.ImageButton btnDownload;
    private javax.swing.JLabel btnSizeFile;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbTextDate;
    private DisenoDePatrones.Vista.Components.PictureBox pictureBox1;
    // End of variables declaration//GEN-END:variables
}
