/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Components;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.ImageIcon;

/**
 *
 * @author LAB-USR-LNORTE
 */
public class PictureBox extends javax.swing.JPanel {
    
    private String image;
    private Image loadedImage;
    private boolean aspectRatio = false;
    private DockPosition dock = DockPosition.CENTER;

    public enum DockPosition {
        TOP_LEFT, TOP_CENTER, TOP_RIGHT,
        CENTER_LEFT, CENTER, CENTER_RIGHT,
        BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT
    }

    public PictureBox() {
        initComponents();
    }

    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
        this.loadedImage = new ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/" + image)).getImage();
        this.repaint();
    }

    public boolean isAspectRatio() {
        return aspectRatio;
    }

    public void setAspectRatio(boolean aspectRatio) {
        this.aspectRatio = aspectRatio;
        this.repaint();
    }

    public DockPosition getDock() {
        return dock;
    }

    public void setDock(DockPosition dock) {
        this.dock = dock;
        this.repaint();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        if (this.loadedImage == null) return;

        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);

        int panelWidth = getWidth();
        int panelHeight = getHeight();

        int imgWidth = this.loadedImage.getWidth(null);
        int imgHeight = this.loadedImage.getHeight(null);

        int drawWidth = panelWidth;
        int drawHeight = panelHeight;

        if (this.aspectRatio) {
            double scale = Math.min((double) panelWidth / imgWidth, (double) panelHeight / imgHeight);
            drawWidth = (int) (imgWidth * scale);
            drawHeight = (int) (imgHeight * scale);
        }

        int x = switch (dock) {
            case TOP_LEFT, CENTER_LEFT, BOTTOM_LEFT -> 0;
            case TOP_CENTER, CENTER, BOTTOM_CENTER -> (panelWidth - drawWidth) / 2;
            case TOP_RIGHT, CENTER_RIGHT, BOTTOM_RIGHT -> panelWidth - drawWidth;
        };

        int y = switch (dock) {
            case TOP_LEFT, TOP_CENTER, TOP_RIGHT -> 0;
            case CENTER_LEFT, CENTER, CENTER_RIGHT -> (panelHeight - drawHeight) / 2;
            case BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT -> panelHeight - drawHeight;
        };

        g2.drawImage(this.loadedImage, x, y, drawWidth, drawHeight, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
