/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.Contents;

/**
 *
 * @author Alex
 */
public class DocumentsForm extends javax.swing.JPanel {

    /**
     * Creates new form FormalitiesForm
     */
    public DocumentsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUploaded = new DisenoDePatrones.Vista.Components.ImageButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnClose = new DisenoDePatrones.Vista.Components.ImageButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUploaded.setBorder(null);
        btnUploaded.setText("");
        btnUploaded.setImageName("Views/NavUpload.png");
        add(btnUploaded, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 37, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 76, 102));
        jLabel3.setText("<html><body style='width:100%;'>Área encargada de la organización, almacenamiento y acceso seguro a la documentación oficial y crítica.</body></html>");
        jLabel3.setPreferredSize(new java.awt.Dimension(488, 42));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 52, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 76, 102));
        jLabel2.setText("GESTION DE DOCUMENTOS IMPORTANTES");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnClose.setBorder(null);
        btnClose.setText("");
        btnClose.setImageName("Views/TramitesClose.png");
        add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 40, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        panelContenedor.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(panelContenedor);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 800, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/Views/Documentos.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 600));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public DisenoDePatrones.Vista.Components.ImageButton btnClose;
    public DisenoDePatrones.Vista.Components.ImageButton btnUploaded;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
