/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.Contents;

/**
 *
 * @author Alex
 */
public class FormalitiesForm extends javax.swing.JPanel {

    /**
     * Creates new form FormalitiesForm
     */
    public FormalitiesForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSIP = new DisenoDePatrones.Vista.Components.ImageButton();
        btnSPL = new DisenoDePatrones.Vista.Components.ImageButton();
        btnST = new DisenoDePatrones.Vista.Components.ImageButton();
        btnDC = new DisenoDePatrones.Vista.Components.ImageButton();
        btnAR = new DisenoDePatrones.Vista.Components.ImageButton();
        btnABD = new DisenoDePatrones.Vista.Components.ImageButton();
        btnCC = new DisenoDePatrones.Vista.Components.ImageButton();
        btnCLA = new DisenoDePatrones.Vista.Components.ImageButton();
        btnDU = new DisenoDePatrones.Vista.Components.ImageButton();
        btnClose = new DisenoDePatrones.Vista.Components.ImageButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSIP.setBorder(null);
        btnSIP.setText("");
        btnSIP.setToolTipText("");
        btnSIP.setImageName("Views/NavTramitar.png");
        add(btnSIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 95, -1, -1));

        btnSPL.setBorder(null);
        btnSPL.setText("");
        btnSPL.setToolTipText("");
        btnSPL.setImageName("Views/NavTramitar.png");
        add(btnSPL, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 145, -1, -1));

        btnST.setBorder(null);
        btnST.setText("");
        btnST.setToolTipText("");
        btnST.setImageName("Views/NavTramitar.png");
        add(btnST, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 195, -1, -1));

        btnDC.setBorder(null);
        btnDC.setText("");
        btnDC.setToolTipText("");
        btnDC.setImageName("Views/NavTramitar.png");
        add(btnDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 245, -1, -1));

        btnAR.setBorder(null);
        btnAR.setText("");
        btnAR.setToolTipText("");
        btnAR.setImageName("Views/NavTramitar.png");
        add(btnAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 295, -1, -1));

        btnABD.setBorder(null);
        btnABD.setText("");
        btnABD.setToolTipText("");
        btnABD.setImageName("Views/NavTramitar.png");
        add(btnABD, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 345, -1, -1));

        btnCC.setBorder(null);
        btnCC.setText("");
        btnCC.setToolTipText("");
        btnCC.setImageName("Views/NavTramitar.png");
        add(btnCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 395, -1, -1));

        btnCLA.setBorder(null);
        btnCLA.setText("");
        btnCLA.setToolTipText("");
        btnCLA.setImageName("Views/NavTramitar.png");
        add(btnCLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 445, -1, -1));

        btnDU.setBorder(null);
        btnDU.setText("");
        btnDU.setToolTipText("");
        btnDU.setImageName("Views/NavTramitar.png");
        add(btnDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 495, -1, -1));

        btnClose.setBorder(null);
        btnClose.setText("");
        btnClose.setImageName("Views/TramitesClose.png");
        add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/Views/Tramites.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 600));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public DisenoDePatrones.Vista.Components.ImageButton btnABD;
    public DisenoDePatrones.Vista.Components.ImageButton btnAR;
    public DisenoDePatrones.Vista.Components.ImageButton btnCC;
    public DisenoDePatrones.Vista.Components.ImageButton btnCLA;
    public DisenoDePatrones.Vista.Components.ImageButton btnClose;
    public DisenoDePatrones.Vista.Components.ImageButton btnDC;
    public DisenoDePatrones.Vista.Components.ImageButton btnDU;
    public DisenoDePatrones.Vista.Components.ImageButton btnSIP;
    public DisenoDePatrones.Vista.Components.ImageButton btnSPL;
    public DisenoDePatrones.Vista.Components.ImageButton btnST;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
