/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.Contents;

/**
 *
 * @author Alex
 */
public class SurveyForm extends javax.swing.JPanel {

    /**
     * Creates new form FormalitiesForm
     */
    public SurveyForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstQ = new javax.swing.ButtonGroup();
        secondQ = new javax.swing.ButtonGroup();
        threeQ = new javax.swing.ButtonGroup();
        fourthQ = new javax.swing.ButtonGroup();
        fiveQ = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        valueDescripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        valueDescripcion1 = new javax.swing.JTextArea();
        btnCancelarE = new DisenoDePatrones.Vista.Components.ImageButton();
        btnEntregar = new DisenoDePatrones.Vista.Components.ImageButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(400, 28));

        fourthQ.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton11.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton11.setText("Nada eficiente");
        jPanel3.add(jRadioButton11);

        fourthQ.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton12.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton12.setText("Poco eficiente");
        jPanel3.add(jRadioButton12);

        fourthQ.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton13.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton13.setText("Neutral");
        jPanel3.add(jRadioButton13);

        fourthQ.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton14.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton14.setText("Eficiente");
        jPanel3.add(jRadioButton14);

        fourthQ.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton15.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton15.setText("Muy Eficiente");
        jPanel3.add(jRadioButton15);

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(343, 28));

        fiveQ.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton6.setText("Si");
        jPanel2.add(jRadioButton6);

        fiveQ.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton7.setText("No");
        jPanel2.add(jRadioButton7);

        fiveQ.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton8.setText("A veces");
        jPanel2.add(jRadioButton8);

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        jPanel1.setPreferredSize(new java.awt.Dimension(343, 28));

        firstQ.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton1.setText("Dificil");
        jPanel1.add(jRadioButton1);

        firstQ.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton2.setText("Regular");
        jPanel1.add(jRadioButton2);

        firstQ.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton3.setText("Fácil");
        jPanel1.add(jRadioButton3);

        firstQ.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton4.setText("Muy Dificil");
        jPanel1.add(jRadioButton4);

        firstQ.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton5.setText("Fácil");
        jPanel1.add(jRadioButton5);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jPanel4.setPreferredSize(new java.awt.Dimension(350, 28));

        secondQ.add(jRadioButton16);
        jRadioButton16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton16.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton16.setText("Siempre");
        jPanel4.add(jRadioButton16);

        secondQ.add(jRadioButton17);
        jRadioButton17.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton17.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton17.setText("Frecuentemente");
        jPanel4.add(jRadioButton17);

        secondQ.add(jRadioButton18);
        jRadioButton18.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton18.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton18.setText("A veces");
        jPanel4.add(jRadioButton18);

        secondQ.add(jRadioButton19);
        jRadioButton19.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton19.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton19.setText("Rara vez");
        jPanel4.add(jRadioButton19);

        secondQ.add(jRadioButton20);
        jRadioButton20.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton20.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton20.setText("Nunca");
        jPanel4.add(jRadioButton20);

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jPanel5.setPreferredSize(new java.awt.Dimension(343, 28));

        threeQ.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton9.setText("Si");
        jPanel5.add(jRadioButton9);

        threeQ.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton10.setText("No");
        jPanel5.add(jRadioButton10);

        threeQ.add(jRadioButton21);
        jRadioButton21.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jRadioButton21.setForeground(new java.awt.Color(64, 76, 102));
        jRadioButton21.setText("Parcialmente");
        jPanel5.add(jRadioButton21);

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(470, 121));

        valueDescripcion.setColumns(20);
        valueDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueDescripcion.setForeground(new java.awt.Color(64, 76, 102));
        valueDescripcion.setRows(5);
        valueDescripcion.setBorder(null);
        jScrollPane1.setViewportView(valueDescripcion);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 350, 80));

        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(470, 121));

        valueDescripcion1.setColumns(20);
        valueDescripcion1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueDescripcion1.setForeground(new java.awt.Color(64, 76, 102));
        valueDescripcion1.setRows(5);
        valueDescripcion1.setBorder(null);
        jScrollPane2.setViewportView(valueDescripcion1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 350, 70));

        btnCancelarE.setBorder(null);
        btnCancelarE.setText("");
        btnCancelarE.setImageName("Views/NavCancelarEn.png");
        add(btnCancelarE, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 544, -1, -1));

        btnEntregar.setBorder(null);
        btnEntregar.setText("");
        btnEntregar.setImageName("Views/NavEntregarEn.png");
        add(btnEntregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 544, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/Views/Encuestas.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(840, 600));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public DisenoDePatrones.Vista.Components.ImageButton btnCancelarE;
    public DisenoDePatrones.Vista.Components.ImageButton btnEntregar;
    public javax.swing.ButtonGroup firstQ;
    public javax.swing.ButtonGroup fiveQ;
    public javax.swing.ButtonGroup fourthQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.ButtonGroup secondQ;
    public javax.swing.ButtonGroup threeQ;
    public javax.swing.JTextArea valueDescripcion;
    public javax.swing.JTextArea valueDescripcion1;
    // End of variables declaration//GEN-END:variables
}
