/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.Reports;

import DisenoDePatrones.Vista.Components.NotifyView;
import DisenoDePatrones.Vista.Layouts.Window.WindowForm;
import java.awt.GridBagConstraints;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Alex
 */
public class NotificationForm extends javax.swing.JPanel {    
    private int count = 0;
    private ArrayList<NotifyView> instances = new ArrayList<>();
    /**
     * Creates new form regulations
     * @param parent
     */
    public NotificationForm(WindowForm parent) {
        initComponents();
        this.contentDragged1.initDragSystem(parent);
    }

    public void addNotification(NotifyView notify) {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridy = count + 1;
        this.jPanel1.add(notify, gbc);
        this.count++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contentDragged1 = new DisenoDePatrones.Vista.Components.ContentDragged();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentDragged1.setPreferredSize(new java.awt.Dimension(400, 30));
        contentDragged1.setTitleBar("Notificaciones");
        add(contentDragged1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        jScrollPane1.setBorder(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 570));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DisenoDePatrones.Vista.Components.ContentDragged contentDragged1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
