/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.Reports;

/**
 *
 * @author Alex
 */
public class ReportStep2 extends javax.swing.JPanel {

    /**
     * Creates new form ReportStep1
     */
    public ReportStep2() {
        initComponents();
    }
    
    public String getAsunto() {
        return this.valueAsunto.getText();
    }
    public String getHora() {
       return this.valueHora.getText();
    }
    public String getFecha() {
        return this.valueFecha.getText();
    }    
    public String getDescripcion() {
        return this.valueDescripcion.getText();
    }
    public void setAsunto(String asunto) {
        this.valueAsunto.setText(asunto);
    }
    public void setHora(String hora) {
        this.valueHora.setText(hora);
    }
    public void setFecha(String fecha) {
        this.valueFecha.setText(fecha);
    }    
    public void setDescripcion(String descripcion) {
        this.valueDescripcion.setText(descripcion);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureBox1 = new DisenoDePatrones.Vista.Components.PictureBox();
        btnPrevious = new DisenoDePatrones.Vista.Components.ImageButton();
        btnCancelar = new DisenoDePatrones.Vista.Components.ImageButton();
        btnNext = new DisenoDePatrones.Vista.Components.ImageButton();
        jLabel2 = new javax.swing.JLabel();
        valueAsunto = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        jLabel3 = new javax.swing.JLabel();
        valueHora = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        jLabel4 = new javax.swing.JLabel();
        valueFecha = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        valueDescripcion = new javax.swing.JTextArea();

        setName(""); // NOI18N
        setOpaque(false);
        setLayout(new java.awt.CardLayout());

        pictureBox1.setImage("Views/Reports/ReportsStepper2.png");
        pictureBox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrevious.setBorder(null);
        btnPrevious.setText("");
        btnPrevious.setImageName("Views/Reports/NavRetroceder.png");
        pictureBox1.add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 543, -1, -1));

        btnCancelar.setBorder(null);
        btnCancelar.setText("");
        btnCancelar.setBackgroundColor(java.awt.Color.white);
        btnCancelar.setImageName("Views/Reports/NavCancelar.png");
        pictureBox1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 543, -1, -1));

        btnNext.setBorder(null);
        btnNext.setText("");
        btnNext.setImageName("Views/Reports/NavSiguiente.png");
        pictureBox1.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 543, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 76, 102));
        jLabel2.setText("Asunto");
        pictureBox1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 196, -1, -1));

        valueAsunto.setFontFamily(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueAsunto.setPlaceholder("...");
        valueAsunto.setText("");
        valueAsunto.setTextForeground(new java.awt.Color(64, 76, 102));
        valueAsunto.setPreferredSize(new java.awt.Dimension(470, 20));
        pictureBox1.add(valueAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 215, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 76, 102));
        jLabel3.setText("Hora");
        pictureBox1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 271, -1, -1));

        valueHora.setFontFamily(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueHora.setPlaceholder("...");
        valueHora.setText("");
        valueHora.setTextForeground(new java.awt.Color(64, 76, 102));
        valueHora.setPreferredSize(new java.awt.Dimension(217, 20));
        pictureBox1.add(valueHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(64, 76, 102));
        jLabel4.setText("Fecha");
        pictureBox1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 271, -1, -1));

        valueFecha.setFontFamily(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueFecha.setPlaceholder("...");
        valueFecha.setText("");
        valueFecha.setTextForeground(new java.awt.Color(64, 76, 102));
        valueFecha.setPreferredSize(new java.awt.Dimension(217, 20));
        pictureBox1.add(valueFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(64, 76, 102));
        jLabel5.setText("Descripción");
        pictureBox1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 346, -1, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(470, 121));

        valueDescripcion.setColumns(20);
        valueDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueDescripcion.setForeground(new java.awt.Color(64, 76, 102));
        valueDescripcion.setRows(5);
        valueDescripcion.setBorder(null);
        valueDescripcion.setOpaque(false);
        jScrollPane1.setViewportView(valueDescripcion);

        pictureBox1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 365, -1, -1));

        add(pictureBox1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public DisenoDePatrones.Vista.Components.ImageButton btnCancelar;
    public DisenoDePatrones.Vista.Components.ImageButton btnNext;
    public DisenoDePatrones.Vista.Components.ImageButton btnPrevious;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private DisenoDePatrones.Vista.Components.PictureBox pictureBox1;
    public DisenoDePatrones.Vista.Components.TextBoxElement.TextBox valueAsunto;
    public javax.swing.JTextArea valueDescripcion;
    public DisenoDePatrones.Vista.Components.TextBoxElement.TextBox valueFecha;
    public DisenoDePatrones.Vista.Components.TextBoxElement.TextBox valueHora;
    // End of variables declaration//GEN-END:variables
}
