/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.Reports;

/**
 *
 * @author Alex
 */
public class ReportStep1 extends javax.swing.JPanel {

    /**
     * Creates new form ReportStep1
     */
    public ReportStep1() {
        initComponents();
    }
    
    public String getDNI() {
        return this.valueDNI.getText();
    }
    public String getNombres() {
       return this.valueNombres.getText();
    }
    public String getApellidos() {
        return this.valueApellidos.getText();
    }    
    public String getEdad() {
        return this.valueEdad.getText();
    }
    public String getProcedencia() {
        return this.valueProcedencia.getText();
    }
    public String getCorreo() {
        return this.valueCorreo.getText();
    }
    public void setDNI(String dni) {
        this.valueDNI.setText(dni);
    }
    public void setNombres(String nombres) {
        this.valueNombres.setText(nombres);
    }
    public void setApellidos(String apellidos) {
        this.valueApellidos.setText(apellidos);
    }    
    public void setEdad(String edad) {
        this.valueEdad.setText(edad);
    }
    public void setProcedencia(String procedencia) {
        this.valueProcedencia.setText(procedencia);
    }
    public void setCorreo(String correo) {
        this.valueCorreo.setText(correo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureBox1 = new DisenoDePatrones.Vista.Components.PictureBox();
        jLabel2 = new javax.swing.JLabel();
        valueDNI = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        jLabel3 = new javax.swing.JLabel();
        valueNombres = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        valueApellidos = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        jLabel4 = new javax.swing.JLabel();
        valueEdad = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        jLabel5 = new javax.swing.JLabel();
        valueProcedencia = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        valueCorreo = new DisenoDePatrones.Vista.Components.TextBoxElement.TextBox();
        btnNext = new DisenoDePatrones.Vista.Components.ImageButton();
        btnCancelar = new DisenoDePatrones.Vista.Components.ImageButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(840, 600));
        setOpaque(false);
        setLayout(new java.awt.CardLayout());

        pictureBox1.setToolTipText("");
        pictureBox1.setImage("Views/Reports/ReportsStepper1.png");
        pictureBox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 76, 102));
        jLabel2.setText("DNI");
        pictureBox1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 209, -1, -1));

        valueDNI.setFontFamily(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueDNI.setPlaceholder("...");
        valueDNI.setText("");
        valueDNI.setTextForeground(new java.awt.Color(64, 76, 102));
        valueDNI.setPreferredSize(new java.awt.Dimension(470, 20));
        pictureBox1.add(valueDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 228, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(64, 76, 102));
        jLabel3.setText("Nombres");
        pictureBox1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 284, -1, -1));

        valueNombres.setFontFamily(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueNombres.setPlaceholder("...");
        valueNombres.setText("");
        valueNombres.setTextForeground(new java.awt.Color(64, 76, 102));
        valueNombres.setPreferredSize(new java.awt.Dimension(217, 20));
        pictureBox1.add(valueNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 303, -1, -1));

        valueApellidos.setFontFamily(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueApellidos.setPlaceholder("...");
        valueApellidos.setText("");
        valueApellidos.setTextForeground(new java.awt.Color(64, 76, 102));
        valueApellidos.setPreferredSize(new java.awt.Dimension(217, 20));
        pictureBox1.add(valueApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 303, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(64, 76, 102));
        jLabel4.setText("Apellidos");
        pictureBox1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 284, -1, -1));

        valueEdad.setFontFamily(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueEdad.setPlaceholder("...");
        valueEdad.setText("");
        valueEdad.setTextForeground(new java.awt.Color(64, 76, 102));
        valueEdad.setPreferredSize(new java.awt.Dimension(217, 20));
        pictureBox1.add(valueEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 378, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(64, 76, 102));
        jLabel5.setText("Edad");
        pictureBox1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 359, -1, -1));

        valueProcedencia.setFontFamily(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueProcedencia.setPlaceholder("...");
        valueProcedencia.setText("");
        valueProcedencia.setTextForeground(new java.awt.Color(64, 76, 102));
        valueProcedencia.setPreferredSize(new java.awt.Dimension(217, 20));
        pictureBox1.add(valueProcedencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 378, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(64, 76, 102));
        jLabel6.setText("Procedencia");
        pictureBox1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 359, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(64, 76, 102));
        jLabel7.setText("Correo Electrónico");
        pictureBox1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 434, -1, -1));

        valueCorreo.setFontFamily(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueCorreo.setPlaceholder("...");
        valueCorreo.setText("");
        valueCorreo.setTextForeground(new java.awt.Color(64, 76, 102));
        valueCorreo.setPreferredSize(new java.awt.Dimension(470, 20));
        pictureBox1.add(valueCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 453, -1, -1));

        btnNext.setBorder(null);
        btnNext.setText("");
        btnNext.setImageName("Views/Reports/NavSiguiente.png");
        pictureBox1.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 543, -1, -1));

        btnCancelar.setBorder(null);
        btnCancelar.setText("");
        btnCancelar.setImageName("Views/Reports/NavCancelar.png");
        pictureBox1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 543, -1, -1));

        add(pictureBox1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public DisenoDePatrones.Vista.Components.ImageButton btnCancelar;
    public DisenoDePatrones.Vista.Components.ImageButton btnNext;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private DisenoDePatrones.Vista.Components.PictureBox pictureBox1;
    public DisenoDePatrones.Vista.Components.TextBoxElement.TextBox valueApellidos;
    public DisenoDePatrones.Vista.Components.TextBoxElement.TextBox valueCorreo;
    public DisenoDePatrones.Vista.Components.TextBoxElement.TextBox valueDNI;
    public DisenoDePatrones.Vista.Components.TextBoxElement.TextBox valueEdad;
    public DisenoDePatrones.Vista.Components.TextBoxElement.TextBox valueNombres;
    public DisenoDePatrones.Vista.Components.TextBoxElement.TextBox valueProcedencia;
    // End of variables declaration//GEN-END:variables
}
