/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.Reports;

import DisenoDePatrones.Vista.Components.PanelRound;
import DisenoDePatrones.Vista.Layouts.Window.WindowForm;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Alex
 */
public class ReportForm extends javax.swing.JPanel {
    /**
     * Creates new form ReportForm
     */
    public ReportForm(WindowForm parent) {
        initComponents();
        this.contentDragged1.initDragSystem(parent);
        iconRegla.setVisible(false);
        
        this.btnCancel.setVisible(false);
    }
    
    public JPanel GetMainContent() {
        return this.ContentMain;
    }

    public JButton GetNextButton() {
        return this.btnNext;
    }
    
    public JButton GetCancelButton() {
        return this.btnCancel;
    }
    
    public JButton GetPreviousButton() {
        return this.btnPrevious;
    }
    
    public JButton GetThanksButton() {
        return this.btnThanks;
    }
    
    public JButton GetOtherReportButton() {
        return this.btnOtherReport;
    }
    
    public JPanel GetNextPanel() {
        return this.input3;
    }
    
    public JPanel GetCancelPanel() {
        return this.input1;
    }
    
    public JPanel GetPreviousPanel() {
        return this.input2;
    }
    
    public JPanel GetThanksPanel() {
        return this.input4;
    }
    
    public JPanel GetOtherReportPanel() {
        return this.input5;
    }
    
    public JLabel GetNotificationButton() {
        return this.btnNotification;
    }
    
    public JLabel GetRegulationsButton() {
        return this.btnRegulations;
    }
    
    public void SetIconRegla(boolean valor){
        this.iconRegla.setVisible(valor);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new DisenoDePatrones.Vista.Components.PanelRound();
        Navbar = new javax.swing.JPanel();
        Content2 = new DisenoDePatrones.Vista.Components.PanelRound();
        tabPerfil = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        tabServices = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        tabInformation = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        iconNoti = new DisenoDePatrones.Vista.Components.PanelRound();
        btnNotification = new javax.swing.JLabel();
        iconRegla = new DisenoDePatrones.Vista.Components.PanelRound();
        btnRegulations = new javax.swing.JLabel();
        ContentMain = new javax.swing.JPanel();
        Footer = new javax.swing.JPanel();
        input1 = new DisenoDePatrones.Vista.Components.PanelRound();
        btnCancel = new javax.swing.JButton();
        input2 = new DisenoDePatrones.Vista.Components.PanelRound();
        btnPrevious = new javax.swing.JButton();
        input3 = new DisenoDePatrones.Vista.Components.PanelRound();
        btnNext = new javax.swing.JButton();
        input4 = new DisenoDePatrones.Vista.Components.PanelRound();
        btnThanks = new javax.swing.JButton();
        input5 = new DisenoDePatrones.Vista.Components.PanelRound();
        btnOtherReport = new javax.swing.JButton();
        contentDragged1 = new DisenoDePatrones.Vista.Components.ContentDragged();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(800, 600));

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setRoundBottomLeft(14);
        Main.setRoundBottomRight(14);
        Main.setRoundTopLeft(14);
        Main.setRoundTopRight(14);
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Navbar.setOpaque(false);
        Navbar.setPreferredSize(new java.awt.Dimension(800, 50));
        Navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Content2.setBackground(new java.awt.Color(245, 245, 245));
        Content2.setRoundBottomLeft(8);
        Content2.setRoundBottomRight(8);
        Content2.setRoundTopLeft(8);
        Content2.setRoundTopRight(8);
        Content2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 6));

        tabPerfil.setBackground(new java.awt.Color(245, 245, 245));
        tabPerfil.setRoundBottomLeft(4);
        tabPerfil.setRoundBottomRight(4);
        tabPerfil.setRoundTopLeft(4);
        tabPerfil.setRoundTopRight(4);
        tabPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPerfilMouseClicked(evt);
            }
        });
        tabPerfil.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 12, 6));

        jLabel2.setForeground(new java.awt.Color(65, 125, 255));
        jLabel2.setText("MI PERFIL");
        tabPerfil.add(jLabel2);

        Content2.add(tabPerfil);

        tabServices.setBackground(new java.awt.Color(65, 125, 255));
        tabServices.setRoundBottomLeft(4);
        tabServices.setRoundBottomRight(4);
        tabServices.setRoundTopLeft(4);
        tabServices.setRoundTopRight(4);
        tabServices.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 12, 6));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SERVICIOS");
        tabServices.add(jLabel3);

        Content2.add(tabServices);

        tabInformation.setBackground(new java.awt.Color(245, 245, 245));
        tabInformation.setRoundBottomLeft(4);
        tabInformation.setRoundBottomRight(4);
        tabInformation.setRoundTopLeft(4);
        tabInformation.setRoundTopRight(4);
        tabInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabInformationMouseClicked(evt);
            }
        });
        tabInformation.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 12, 6));

        jLabel4.setForeground(new java.awt.Color(65, 125, 255));
        jLabel4.setText("INFORMACION");
        tabInformation.add(jLabel4);

        Content2.add(tabInformation);

        Navbar.add(Content2, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 5, -1, -1));

        iconNoti.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        iconNoti.setRoundBottomLeft(8);
        iconNoti.setRoundBottomRight(8);
        iconNoti.setRoundTopLeft(8);
        iconNoti.setRoundTopRight(8);
        iconNoti.setLayout(new java.awt.CardLayout());

        btnNotification.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/notificationO.png"))); // NOI18N
        iconNoti.add(btnNotification, "card2");

        Navbar.add(iconNoti, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 30, 30));

        iconRegla.setRoundBottomLeft(8);
        iconRegla.setRoundBottomRight(8);
        iconRegla.setRoundTopLeft(8);
        iconRegla.setRoundTopRight(8);
        iconRegla.setLayout(new java.awt.CardLayout());

        btnRegulations.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/reglamentos.png"))); // NOI18N
        iconRegla.add(btnRegulations, "card2");

        Navbar.add(iconRegla, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 10, 30, 30));

        Main.add(Navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 800, -1));

        ContentMain.setOpaque(false);
        ContentMain.setPreferredSize(new java.awt.Dimension(800, 423));
        ContentMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Main.add(ContentMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, 800, -1));

        Footer.setOpaque(false);
        Footer.setPreferredSize(new java.awt.Dimension(800, 77));
        Footer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 16));

        input1.setBackground(new java.awt.Color(255, 255, 255));
        input1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(65, 125, 255), 2, true));
        input1.setOpaque(true);
        input1.setPreferredSize(new java.awt.Dimension(216, 36));
        input1.setLayout(new java.awt.CardLayout());

        btnCancel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(65, 125, 255));
        btnCancel.setText("CANCELAR");
        btnCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        btnCancel.setFocusPainted(false);
        input1.add(btnCancel, "card2");

        Footer.add(input1);

        input2.setBackground(new java.awt.Color(65, 125, 255));
        input2.setPreferredSize(new java.awt.Dimension(216, 36));
        input2.setRoundBottomLeft(4);
        input2.setRoundBottomRight(4);
        input2.setRoundTopLeft(4);
        input2.setRoundTopRight(4);
        input2.setLayout(new java.awt.CardLayout());

        btnPrevious.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious.setText("RETROCEDER");
        btnPrevious.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPrevious.setBorderPainted(false);
        btnPrevious.setContentAreaFilled(false);
        btnPrevious.setFocusPainted(false);
        input2.add(btnPrevious, "card2");

        Footer.add(input2);

        input3.setBackground(new java.awt.Color(65, 125, 255));
        input3.setPreferredSize(new java.awt.Dimension(216, 36));
        input3.setRoundBottomLeft(4);
        input3.setRoundBottomRight(4);
        input3.setRoundTopLeft(4);
        input3.setRoundTopRight(4);
        input3.setLayout(new java.awt.CardLayout());

        btnNext.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("SIGUIENTE");
        btnNext.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNext.setBorderPainted(false);
        btnNext.setContentAreaFilled(false);
        btnNext.setFocusPainted(false);
        input3.add(btnNext, "card2");

        Footer.add(input3);

        input4.setBackground(new java.awt.Color(65, 125, 255));
        input4.setPreferredSize(new java.awt.Dimension(216, 36));
        input4.setRoundBottomLeft(4);
        input4.setRoundBottomRight(4);
        input4.setRoundTopLeft(4);
        input4.setRoundTopRight(4);
        input4.setLayout(new java.awt.CardLayout());

        btnThanks.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnThanks.setForeground(new java.awt.Color(255, 255, 255));
        btnThanks.setText("GRACIAS");
        btnThanks.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnThanks.setBorderPainted(false);
        btnThanks.setContentAreaFilled(false);
        btnThanks.setFocusPainted(false);
        input4.add(btnThanks, "card2");

        Footer.add(input4);

        input5.setBackground(new java.awt.Color(65, 125, 255));
        input5.setPreferredSize(new java.awt.Dimension(216, 36));
        input5.setRoundBottomLeft(4);
        input5.setRoundBottomRight(4);
        input5.setRoundTopLeft(4);
        input5.setRoundTopRight(4);
        input5.setLayout(new java.awt.CardLayout());

        btnOtherReport.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnOtherReport.setForeground(new java.awt.Color(255, 255, 255));
        btnOtherReport.setText("HACER OTRO REPORTE");
        btnOtherReport.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnOtherReport.setBorderPainted(false);
        btnOtherReport.setContentAreaFilled(false);
        btnOtherReport.setFocusPainted(false);
        input5.add(btnOtherReport, "card2");

        Footer.add(input5);

        Main.add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 521, -1, 80));

        contentDragged1.setTitleBar("Gestion Ciudadana");
        Main.add(contentDragged1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabInformationMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Has hecho clic en la pestaña Información.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_tabInformationMouseClicked

    private void tabPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPerfilMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Has hecho clic en la pestaña Información.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_tabPerfilMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DisenoDePatrones.Vista.Components.PanelRound Content2;
    private javax.swing.JPanel ContentMain;
    private javax.swing.JPanel Footer;
    private DisenoDePatrones.Vista.Components.PanelRound Main;
    private javax.swing.JPanel Navbar;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel btnNotification;
    private javax.swing.JButton btnOtherReport;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel btnRegulations;
    private javax.swing.JButton btnThanks;
    private DisenoDePatrones.Vista.Components.ContentDragged contentDragged1;
    private DisenoDePatrones.Vista.Components.PanelRound iconNoti;
    private DisenoDePatrones.Vista.Components.PanelRound iconRegla;
    private DisenoDePatrones.Vista.Components.PanelRound input1;
    private DisenoDePatrones.Vista.Components.PanelRound input2;
    private DisenoDePatrones.Vista.Components.PanelRound input3;
    private DisenoDePatrones.Vista.Components.PanelRound input4;
    private DisenoDePatrones.Vista.Components.PanelRound input5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private DisenoDePatrones.Vista.Components.PanelRound tabInformation;
    private DisenoDePatrones.Vista.Components.PanelRound tabPerfil;
    private DisenoDePatrones.Vista.Components.PanelRound tabServices;
    // End of variables declaration//GEN-END:variables
}
