/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.Reports;
/**
 *
 * @author Alex
 */
public class ReportStep3 extends javax.swing.JPanel {

    /**
     * Creates new form ReportStep1
     */
    public ReportStep3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureBox1 = new DisenoDePatrones.Vista.Components.PictureBox();
        btnRepeat = new DisenoDePatrones.Vista.Components.ImageButton();
        btnThanks = new DisenoDePatrones.Vista.Components.ImageButton();

        setLayout(new java.awt.CardLayout());

        pictureBox1.setImage("Views/Reports/ReportsStepper3.png");
        pictureBox1.setName(""); // NOI18N
        pictureBox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRepeat.setBorder(null);
        btnRepeat.setText("");
        btnRepeat.setImageName("Views/Reports/NavRepeat.png");
        pictureBox1.add(btnRepeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 543, -1, -1));

        btnThanks.setBorder(null);
        btnThanks.setText("");
        btnThanks.setImageName("Views/Reports/NavGracias.png");
        pictureBox1.add(btnThanks, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 543, -1, -1));

        add(pictureBox1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public DisenoDePatrones.Vista.Components.ImageButton btnRepeat;
    public DisenoDePatrones.Vista.Components.ImageButton btnThanks;
    private DisenoDePatrones.Vista.Components.PictureBox pictureBox1;
    // End of variables declaration//GEN-END:variables
}
