/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.MainForm;

/**
 *
 * @author Alex
 */
public class InformationNavForm extends javax.swing.JPanel {

    /**
     * Creates new form ServicesNavForm
     */
    public InformationNavForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIInformation = new DisenoDePatrones.Vista.Components.ImageButton();
        btnIResources = new DisenoDePatrones.Vista.Components.ImageButton();
        btnICitizens = new DisenoDePatrones.Vista.Components.ImageButton();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 76, 102));
        jLabel1.setText("Copyright © 2025 Gestión de Ciudadana. Todos los derechos reservados.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 498, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 76, 102));
        jLabel2.setText("INFORMACIÓN DE LA CIUDADANÍA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 20, -1, -1));

        btnIInformation.setBorder(null);
        btnIInformation.setText("");
        btnIInformation.setImageName("Servicios/CardMDocumentos.png");
        add(btnIInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 72, -1, -1));

        btnIResources.setBorder(null);
        btnIResources.setText("");
        btnIResources.setImageName("Servicios/CardMRecursos.png");
        add(btnIResources, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 72, -1, -1));

        btnICitizens.setBorder(null);
        btnICitizens.setText("");
        btnICitizens.setImageName("Servicios/CardMCiudadania.png");
        add(btnICitizens, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 72, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public DisenoDePatrones.Vista.Components.ImageButton btnICitizens;
    public DisenoDePatrones.Vista.Components.ImageButton btnIInformation;
    public DisenoDePatrones.Vista.Components.ImageButton btnIResources;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
