/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.MainForm;

import DisenoDePatrones.Vista.Layouts.Window.WindowForm;
import javax.swing.JPanel;

/**
 *
 * @author Alex
 */
public class MainMenuForm extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public MainMenuForm(WindowForm window) {
        initComponents();
        this.contentDragged1.initDragSystem(window);
    }
    
    public JPanel BodyApplication() {
        return this.BodyApplication;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentDragged1 = new DisenoDePatrones.Vista.Components.ContentDragged();
        BodyApplication = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentDragged1.setPreferredSize(new java.awt.Dimension(840, 30));
        contentDragged1.setTitleBar("GESTION CIUDADANA");
        add(contentDragged1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BodyApplication.setBackground(new java.awt.Color(255, 255, 255));
        BodyApplication.setPreferredSize(new java.awt.Dimension(840, 600));
        BodyApplication.setLayout(new java.awt.CardLayout());
        add(BodyApplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BodyApplication;
    private DisenoDePatrones.Vista.Components.ContentDragged contentDragged1;
    // End of variables declaration//GEN-END:variables
}
