/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.MainForm;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Alex
 */
public class NavigationForm extends javax.swing.JPanel {

    /**
     * Creates new form ServicesForm
     */
    public NavigationForm() {
        initComponents();
    }
    
    public JButton GetServicesButton() {
        return this.btnNavServicios;
    }
    
    public JButton GetPerfilButton() {
        return this.btnNavPerfil;
    }
     
    public JButton GetInformationButton() {
        return this.btnNavInfo;
    }
    
    public JButton GetRegulationsButton() {
        return this.btnRegulation;
    }
    
    public JButton GetNotificationsButton() {
        return this.btnNotification;
    }
    
    public JPanel GetContentBody() {
        return this.pnContentNav;
    }
    
    public void SetIconRegla(boolean state) {
        this.btnRegulation.setVisible(state);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNavbar = new javax.swing.JPanel();
        panelRound1 = new DisenoDePatrones.Vista.Components.PanelRound();
        btnNavInfo = new DisenoDePatrones.Vista.Components.ImageButton();
        btnNavPerfil = new DisenoDePatrones.Vista.Components.ImageButton();
        btnNavServicios = new DisenoDePatrones.Vista.Components.ImageButton();
        btnRegulation = new DisenoDePatrones.Vista.Components.ImageButton();
        btnNotification = new DisenoDePatrones.Vista.Components.ImageButton();
        pnContentNav = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnNavbar.setOpaque(false);
        pnNavbar.setPreferredSize(new java.awt.Dimension(840, 63));
        pnNavbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(245, 245, 245));
        panelRound1.setPreferredSize(new java.awt.Dimension(450, 53));
        panelRound1.setRoundBottomLeft(8);
        panelRound1.setRoundBottomRight(8);
        panelRound1.setRoundTopLeft(8);
        panelRound1.setRoundTopRight(8);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNavInfo.setBackground(new java.awt.Color(65, 125, 255));
        btnNavInfo.setBorder(null);
        btnNavInfo.setForeground(new java.awt.Color(65, 125, 255));
        btnNavInfo.setText("INFORMACIÓN");
        btnNavInfo.setBackgroundColor(new java.awt.Color(245, 245, 245));
        btnNavInfo.setBorderRadius(4);
        btnNavInfo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnNavInfo.setPreferredSize(new java.awt.Dimension(138, 37));
        panelRound1.add(btnNavInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 8, -1, -1));

        btnNavPerfil.setBackground(new java.awt.Color(65, 125, 255));
        btnNavPerfil.setBorder(null);
        btnNavPerfil.setForeground(new java.awt.Color(65, 125, 255));
        btnNavPerfil.setText("MI PERFIL");
        btnNavPerfil.setBackgroundColor(new java.awt.Color(245, 245, 245));
        btnNavPerfil.setBorderRadius(4);
        btnNavPerfil.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnNavPerfil.setPreferredSize(new java.awt.Dimension(138, 37));
        panelRound1.add(btnNavPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, -1, -1));

        btnNavServicios.setBackground(new java.awt.Color(65, 125, 255));
        btnNavServicios.setBorder(null);
        btnNavServicios.setForeground(new java.awt.Color(65, 125, 255));
        btnNavServicios.setText("SERVICIOS");
        btnNavServicios.setBackgroundColor(new java.awt.Color(245, 245, 245));
        btnNavServicios.setBorderRadius(4);
        btnNavServicios.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnNavServicios.setPreferredSize(new java.awt.Dimension(138, 37));
        panelRound1.add(btnNavServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 8, -1, -1));

        pnNavbar.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 5, -1, -1));

        btnRegulation.setBorder(null);
        btnRegulation.setText("");
        btnRegulation.setImageName("reglamentos.png");
        btnRegulation.setPreferredSize(new java.awt.Dimension(53, 53));
        pnNavbar.add(btnRegulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 5, -1, -1));

        btnNotification.setBorder(null);
        btnNotification.setText("");
        btnNotification.setImageName("notificationO.png");
        btnNotification.setName(""); // NOI18N
        btnNotification.setPreferredSize(new java.awt.Dimension(53, 53));
        pnNavbar.add(btnNotification, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 5, -1, -1));

        add(pnNavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnContentNav.setOpaque(false);
        pnContentNav.setPreferredSize(new java.awt.Dimension(840, 537));
        pnContentNav.setLayout(new java.awt.CardLayout());
        add(pnContentNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public DisenoDePatrones.Vista.Components.ImageButton btnNavInfo;
    public DisenoDePatrones.Vista.Components.ImageButton btnNavPerfil;
    public DisenoDePatrones.Vista.Components.ImageButton btnNavServicios;
    private DisenoDePatrones.Vista.Components.ImageButton btnNotification;
    private DisenoDePatrones.Vista.Components.ImageButton btnRegulation;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound1;
    private javax.swing.JPanel pnContentNav;
    private javax.swing.JPanel pnNavbar;
    // End of variables declaration//GEN-END:variables
}
