/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.MainForm;

/**
 *
 * @author Alex
 */
public class PerfilNavForm extends javax.swing.JPanel {

    /**
     * Creates new form ServicesNavForm
     */
    public PerfilNavForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbNombres = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbDNI = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbProcedencia = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbApellidos = new javax.swing.JLabel();
        lbEdad = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 76, 102));
        jLabel1.setText("Copyright © 2025 Gestión de Ciudadana. Todos los derechos reservados.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 498, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 76, 102));
        jLabel2.setText("PERFIL DEL CIUDADANO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 20, -1, -1));

        jLabel4.setBackground(new java.awt.Color(51, 255, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/Profile.png"))); // NOI18N
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setPreferredSize(new java.awt.Dimension(344, 300));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 125, -1, -1));

        lbNombres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbNombres.setForeground(new java.awt.Color(64, 76, 102));
        lbNombres.setText("NOMBRES");
        add(lbNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 149, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(64, 76, 102));
        jLabel6.setText("Nombres");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 125, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(64, 76, 102));
        jLabel7.setText("Correo Electrónico");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 377, -1, -1));

        lbEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(64, 76, 102));
        lbEmail.setText("CORREO@CORREO.COM");
        add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 401, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(64, 76, 102));
        jLabel9.setText("DNI");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 251, -1, -1));

        lbDNI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbDNI.setForeground(new java.awt.Color(64, 76, 102));
        lbDNI.setText("00000000");
        add(lbDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 275, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(64, 76, 102));
        jLabel11.setText("Procedencia");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 251, -1, 20));

        lbProcedencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbProcedencia.setForeground(new java.awt.Color(64, 76, 102));
        lbProcedencia.setText("PROCEDENCIA");
        add(lbProcedencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 275, -1, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(64, 76, 102));
        jLabel13.setText("Apellidos");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 188, -1, -1));

        lbApellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbApellidos.setForeground(new java.awt.Color(64, 76, 102));
        lbApellidos.setText("APELLIDOS");
        add(lbApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 212, -1, -1));

        lbEdad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbEdad.setForeground(new java.awt.Color(64, 76, 102));
        lbEdad.setText("EDAD");
        add(lbEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 338, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(64, 76, 102));
        jLabel16.setText("Edad");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 314, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lbApellidos;
    public javax.swing.JLabel lbDNI;
    public javax.swing.JLabel lbEdad;
    public javax.swing.JLabel lbEmail;
    public javax.swing.JLabel lbNombres;
    public javax.swing.JLabel lbProcedencia;
    // End of variables declaration//GEN-END:variables
}
