/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts.MainForm;

/**
 *
 * @author Alex
 */
public class ServicesNavForm extends javax.swing.JPanel {

    /**
     * Creates new form ServicesNavForm
     */
    public ServicesNavForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSDocuments = new DisenoDePatrones.Vista.Components.ImageButton();
        btnSReports = new DisenoDePatrones.Vista.Components.ImageButton();
        btnSSurvey = new DisenoDePatrones.Vista.Components.ImageButton();
        btnSFormalities = new DisenoDePatrones.Vista.Components.ImageButton();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 76, 102));
        jLabel1.setText("Copyright © 2025 Gestión de Ciudadana. Todos los derechos reservados.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 498, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 76, 102));
        jLabel2.setText("SERVICIOS DE GESTION CIUDADANA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 20, -1, -1));

        btnSDocuments.setBorder(null);
        btnSDocuments.setText("");
        btnSDocuments.setImageName("Servicios/CardLDocumentos.png");
        add(btnSDocuments, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 72, -1, -1));

        btnSReports.setBorder(null);
        btnSReports.setText("");
        btnSReports.setImageName("Servicios/CardLReportes.png");
        add(btnSReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 72, -1, -1));

        btnSSurvey.setBorder(null);
        btnSSurvey.setText("");
        btnSSurvey.setImageName("Servicios/CardLEncuestas.png");
        add(btnSSurvey, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 72, -1, -1));

        btnSFormalities.setBorder(null);
        btnSFormalities.setText("");
        btnSFormalities.setImageName("Servicios/CardLTramites.png");
        add(btnSFormalities, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 72, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public DisenoDePatrones.Vista.Components.ImageButton btnSDocuments;
    public DisenoDePatrones.Vista.Components.ImageButton btnSFormalities;
    public DisenoDePatrones.Vista.Components.ImageButton btnSReports;
    public DisenoDePatrones.Vista.Components.ImageButton btnSSurvey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
