/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts;

import java.awt.Color;

/**
 *
 * @author Alex
 */
public class ReportStep2 extends javax.swing.JPanel {

    /**
     * Creates new form ReportStep1
     */
    public ReportStep2() {
        initComponents();
        Color transparent = new Color(0, 0, 0, 0);
        
        this.setBackground(transparent);
        this.Stepper.setBackground(transparent);
        this.Content.setBackground(transparent);
    }
    
    public String getAsunto() {
        return this.valueAsunto.getText();
    }
    public String getHora() {
       return this.valueHora.getText();
    }
    public String getFecha() {
        return this.valueFecha.getText();
    }    
    public String getDescripcion() {
        return this.valueDescripcion.getText();
    }
    public void setAsunto(String asunto) {
        this.valueAsunto.setText(asunto);
    }
    public void setHora(String hora) {
        this.valueHora.setText(hora);
    }
    public void setFecha(String fecha) {
        this.valueFecha.setText(fecha);
    }    
    public void setDescripcion(String descripcion) {
        this.valueDescripcion.setText(descripcion);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Stepper = new javax.swing.JPanel();
        panelRound2 = new DisenoDePatrones.Vista.Components.PanelRound();
        Step1Label = new javax.swing.JLabel();
        BarProgress = new DisenoDePatrones.Vista.Components.PanelRound();
        decor = new DisenoDePatrones.Vista.Components.PanelRound();
        panelRound1 = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BarProgress1 = new DisenoDePatrones.Vista.Components.PanelRound();
        decor1 = new DisenoDePatrones.Vista.Components.PanelRound();
        panelRound3 = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();
        InputNombre = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        valueAsunto = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        InputNombre3 = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        valueHora = new javax.swing.JTextField();
        InputNombre2 = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        valueFecha = new javax.swing.JTextField();
        InputNombre1 = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        valueDescripcion = new javax.swing.JTextArea();

        Stepper.setOpaque(false);
        Stepper.setPreferredSize(new java.awt.Dimension(800, 80));
        Stepper.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        panelRound2.setBackground(new java.awt.Color(65, 125, 255));
        panelRound2.setPreferredSize(new java.awt.Dimension(40, 40));
        panelRound2.setRoundBottomLeft(40);
        panelRound2.setRoundBottomRight(40);
        panelRound2.setRoundTopLeft(40);
        panelRound2.setRoundTopRight(40);
        panelRound2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 8));

        Step1Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Step1Label.setForeground(new java.awt.Color(255, 255, 255));
        Step1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/check.png"))); // NOI18N
        panelRound2.add(Step1Label);

        Stepper.add(panelRound2);

        BarProgress.setBackground(new java.awt.Color(197, 205, 216));
        BarProgress.setPreferredSize(new java.awt.Dimension(205, 6));
        BarProgress.setRoundBottomLeft(6);
        BarProgress.setRoundBottomRight(6);
        BarProgress.setRoundTopLeft(6);
        BarProgress.setRoundTopRight(6);
        BarProgress.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decor.setBackground(new java.awt.Color(65, 125, 255));
        decor.setPreferredSize(new java.awt.Dimension(205, 6));
        decor.setRoundBottomLeft(6);
        decor.setRoundBottomRight(6);
        decor.setRoundTopLeft(6);
        decor.setRoundTopRight(6);

        javax.swing.GroupLayout decorLayout = new javax.swing.GroupLayout(decor);
        decor.setLayout(decorLayout);
        decorLayout.setHorizontalGroup(
            decorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        decorLayout.setVerticalGroup(
            decorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        BarProgress.add(decor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Stepper.add(BarProgress);

        panelRound1.setBackground(new java.awt.Color(65, 125, 255));
        panelRound1.setOpaque(true);
        panelRound1.setPreferredSize(new java.awt.Dimension(205, 40));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 2));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("2");
        panelRound1.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tema de Reporte");
        panelRound1.add(jLabel1);

        Stepper.add(panelRound1);

        BarProgress1.setBackground(new java.awt.Color(64, 76, 102));
        BarProgress1.setPreferredSize(new java.awt.Dimension(205, 6));
        BarProgress1.setRoundBottomLeft(6);
        BarProgress1.setRoundBottomRight(6);
        BarProgress1.setRoundTopLeft(6);
        BarProgress1.setRoundTopRight(6);
        BarProgress1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decor1.setBackground(new java.awt.Color(65, 125, 255));
        decor1.setPreferredSize(new java.awt.Dimension(102, 6));
        decor1.setRoundBottomLeft(6);
        decor1.setRoundBottomRight(6);
        decor1.setRoundTopLeft(6);
        decor1.setRoundTopRight(6);

        javax.swing.GroupLayout decor1Layout = new javax.swing.GroupLayout(decor1);
        decor1.setLayout(decor1Layout);
        decor1Layout.setHorizontalGroup(
            decor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        decor1Layout.setVerticalGroup(
            decor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        BarProgress1.add(decor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Stepper.add(BarProgress1);

        panelRound3.setBackground(new java.awt.Color(64, 76, 102));
        panelRound3.setPreferredSize(new java.awt.Dimension(40, 40));
        panelRound3.setRoundBottomLeft(40);
        panelRound3.setRoundBottomRight(40);
        panelRound3.setRoundTopLeft(40);
        panelRound3.setRoundTopRight(40);
        panelRound3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 2));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("3");
        panelRound3.add(jLabel4);

        Stepper.add(panelRound3);

        Content.setOpaque(false);
        Content.setPreferredSize(new java.awt.Dimension(800, 80));
        Content.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        InputNombre.setBackground(new java.awt.Color(245, 245, 245));
        InputNombre.setPreferredSize(new java.awt.Dimension(492, 65));
        InputNombre.setRoundBottomLeft(6);
        InputNombre.setRoundBottomRight(6);
        InputNombre.setRoundTopLeft(6);
        InputNombre.setRoundTopRight(6);
        InputNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(64, 76, 102));
        jLabel5.setText("Asunto");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        InputNombre.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        valueAsunto.setBackground(new java.awt.Color(245, 245, 245));
        valueAsunto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueAsunto.setForeground(new java.awt.Color(64, 76, 102));
        valueAsunto.setText("...");
        valueAsunto.setBorder(null);
        valueAsunto.setPreferredSize(new java.awt.Dimension(492, 22));
        InputNombre.add(valueAsunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 460, -1));

        Content.add(InputNombre);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(492, 65));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        InputNombre3.setBackground(new java.awt.Color(245, 245, 245));
        InputNombre3.setPreferredSize(new java.awt.Dimension(492, 65));
        InputNombre3.setRoundBottomLeft(6);
        InputNombre3.setRoundBottomRight(6);
        InputNombre3.setRoundTopLeft(6);
        InputNombre3.setRoundTopRight(6);
        InputNombre3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(64, 76, 102));
        jLabel8.setText("Hora");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        InputNombre3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        valueHora.setBackground(new java.awt.Color(245, 245, 245));
        valueHora.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueHora.setForeground(new java.awt.Color(64, 76, 102));
        valueHora.setText("...");
        valueHora.setBorder(null);
        valueHora.setPreferredSize(new java.awt.Dimension(492, 22));
        InputNombre3.add(valueHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 210, -1));

        jPanel1.add(InputNombre3);

        InputNombre2.setBackground(new java.awt.Color(245, 245, 245));
        InputNombre2.setPreferredSize(new java.awt.Dimension(492, 65));
        InputNombre2.setRoundBottomLeft(6);
        InputNombre2.setRoundBottomRight(6);
        InputNombre2.setRoundTopLeft(6);
        InputNombre2.setRoundTopRight(6);
        InputNombre2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(64, 76, 102));
        jLabel7.setText("Fecha");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        InputNombre2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        valueFecha.setBackground(new java.awt.Color(245, 245, 245));
        valueFecha.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueFecha.setForeground(new java.awt.Color(64, 76, 102));
        valueFecha.setText("...");
        valueFecha.setBorder(null);
        valueFecha.setPreferredSize(new java.awt.Dimension(492, 22));
        InputNombre2.add(valueFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 210, -1));

        jPanel1.add(InputNombre2);

        Content.add(jPanel1);

        InputNombre1.setBackground(new java.awt.Color(245, 245, 245));
        InputNombre1.setPreferredSize(new java.awt.Dimension(492, 150));
        InputNombre1.setRoundBottomLeft(6);
        InputNombre1.setRoundBottomRight(6);
        InputNombre1.setRoundTopLeft(6);
        InputNombre1.setRoundTopRight(6);
        InputNombre1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(64, 76, 102));
        jLabel6.setText("Descripción");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel6.setPreferredSize(new java.awt.Dimension(492, 20));
        InputNombre1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, 470, -1));

        valueDescripcion.setBackground(new java.awt.Color(245, 245, 245));
        valueDescripcion.setColumns(20);
        valueDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueDescripcion.setForeground(new java.awt.Color(64, 76, 102));
        valueDescripcion.setLineWrap(true);
        valueDescripcion.setRows(5);
        valueDescripcion.setText("...");
        valueDescripcion.setBorder(null);
        jScrollPane1.setViewportView(valueDescripcion);

        InputNombre1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 470, 110));

        Content.add(InputNombre1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stepper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Stepper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DisenoDePatrones.Vista.Components.PanelRound BarProgress;
    private DisenoDePatrones.Vista.Components.PanelRound BarProgress1;
    private javax.swing.JPanel Content;
    private DisenoDePatrones.Vista.Components.PanelRound InputNombre;
    private DisenoDePatrones.Vista.Components.PanelRound InputNombre1;
    private DisenoDePatrones.Vista.Components.PanelRound InputNombre2;
    private DisenoDePatrones.Vista.Components.PanelRound InputNombre3;
    private javax.swing.JLabel Step1Label;
    private javax.swing.JPanel Stepper;
    private DisenoDePatrones.Vista.Components.PanelRound decor;
    private DisenoDePatrones.Vista.Components.PanelRound decor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound1;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound2;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound3;
    private javax.swing.JTextField valueAsunto;
    private javax.swing.JTextArea valueDescripcion;
    private javax.swing.JTextField valueFecha;
    private javax.swing.JTextField valueHora;
    // End of variables declaration//GEN-END:variables
}
