/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts;

import java.awt.Color;

/**
 *
 * @author Alex
 */
public class ReportStep1 extends javax.swing.JPanel {

    /**
     * Creates new form ReportStep1
     */
    public ReportStep1() {
        initComponents();
        Color transparent = new Color(0, 0, 0, 0);
        
        this.setBackground(transparent);
        this.Stepper.setBackground(transparent);
        this.Content.setBackground(transparent);
    }
    
    public String getDNI() {
        return this.valueDNI.getText();
    }
    public String getNombres() {
       return this.valueNombres.getText();
    }
    public String getApellidos() {
        return this.valueApellidos.getText();
    }    
    public String getEdad() {
        return this.valueEdad.getText();
    }
    public String getProcedencia() {
        return this.valueProcedencia.getText();
    }
    public String getCorreo() {
        return this.valueCorreo.getText();
    }
    public void setDNI(String dni) {
        this.valueDNI.setText(dni);
    }
    public void setNombres(String nombres) {
        this.valueNombres.setText(nombres);
    }
    public void setApellidos(String apellidos) {
        this.valueApellidos.setText(apellidos);
    }    
    public void setEdad(String edad) {
        this.valueEdad.setText(edad);
    }
    public void setProcedencia(String procedencia) {
        this.valueProcedencia.setText(procedencia);
    }
    public void setCorreo(String correo) {
        this.valueCorreo.setText(correo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Stepper = new javax.swing.JPanel();
        panelRound1 = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BarProgress = new DisenoDePatrones.Vista.Components.PanelRound();
        decor = new DisenoDePatrones.Vista.Components.PanelRound();
        panelRound2 = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        BarProgress1 = new DisenoDePatrones.Vista.Components.PanelRound();
        panelRound3 = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();
        InputDNI = new DisenoDePatrones.Vista.Components.PanelRound();
        nameDNI = new javax.swing.JLabel();
        valueDNI = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        InputNombre = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        valueNombres = new javax.swing.JTextField();
        InputApellidos = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        valueApellidos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        InputEdad = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        valueEdad = new javax.swing.JTextField();
        InputProcedencia = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        valueProcedencia = new javax.swing.JTextField();
        InputCorreo = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel6 = new javax.swing.JLabel();
        valueCorreo = new javax.swing.JTextField();

        setOpaque(false);

        Stepper.setOpaque(false);
        Stepper.setPreferredSize(new java.awt.Dimension(800, 80));
        Stepper.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        panelRound1.setBackground(new java.awt.Color(38, 38, 38));
        panelRound1.setPreferredSize(new java.awt.Dimension(205, 40));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 2));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("1");
        panelRound1.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos Personales");
        panelRound1.add(jLabel1);

        Stepper.add(panelRound1);

        BarProgress.setBackground(new java.awt.Color(197, 205, 216));
        BarProgress.setPreferredSize(new java.awt.Dimension(205, 6));
        BarProgress.setRoundBottomLeft(6);
        BarProgress.setRoundBottomRight(6);
        BarProgress.setRoundTopLeft(6);
        BarProgress.setRoundTopRight(6);
        BarProgress.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decor.setBackground(new java.awt.Color(38, 38, 38));
        decor.setPreferredSize(new java.awt.Dimension(102, 6));
        decor.setRoundBottomLeft(6);
        decor.setRoundBottomRight(6);
        decor.setRoundTopLeft(6);
        decor.setRoundTopRight(6);

        javax.swing.GroupLayout decorLayout = new javax.swing.GroupLayout(decor);
        decor.setLayout(decorLayout);
        decorLayout.setHorizontalGroup(
            decorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );
        decorLayout.setVerticalGroup(
            decorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        BarProgress.add(decor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Stepper.add(BarProgress);

        panelRound2.setBackground(new java.awt.Color(38, 38, 38));
        panelRound2.setPreferredSize(new java.awt.Dimension(40, 40));
        panelRound2.setRoundBottomLeft(40);
        panelRound2.setRoundBottomRight(40);
        panelRound2.setRoundTopLeft(40);
        panelRound2.setRoundTopRight(40);
        panelRound2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 2));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("2");
        panelRound2.add(jLabel3);

        Stepper.add(panelRound2);

        BarProgress1.setBackground(new java.awt.Color(197, 205, 216));
        BarProgress1.setPreferredSize(new java.awt.Dimension(205, 6));
        BarProgress1.setRoundBottomLeft(6);
        BarProgress1.setRoundBottomRight(6);
        BarProgress1.setRoundTopLeft(6);
        BarProgress1.setRoundTopRight(6);
        BarProgress1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Stepper.add(BarProgress1);

        panelRound3.setBackground(new java.awt.Color(38, 38, 38));
        panelRound3.setPreferredSize(new java.awt.Dimension(40, 40));
        panelRound3.setRoundBottomLeft(40);
        panelRound3.setRoundBottomRight(40);
        panelRound3.setRoundTopLeft(40);
        panelRound3.setRoundTopRight(40);
        panelRound3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 2));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("3");
        panelRound3.add(jLabel4);

        Stepper.add(panelRound3);

        Content.setOpaque(false);
        Content.setPreferredSize(new java.awt.Dimension(800, 80));
        Content.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        InputDNI.setBackground(new java.awt.Color(38, 38, 38));
        InputDNI.setPreferredSize(new java.awt.Dimension(492, 65));
        InputDNI.setRoundBottomLeft(6);
        InputDNI.setRoundBottomRight(6);
        InputDNI.setRoundTopLeft(6);
        InputDNI.setRoundTopRight(6);
        InputDNI.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameDNI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameDNI.setForeground(new java.awt.Color(197, 205, 216));
        nameDNI.setText("DNI");
        nameDNI.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        InputDNI.add(nameDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        valueDNI.setBackground(new java.awt.Color(38, 38, 38));
        valueDNI.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueDNI.setForeground(new java.awt.Color(255, 255, 255));
        valueDNI.setText("...");
        valueDNI.setBorder(null);
        valueDNI.setPreferredSize(new java.awt.Dimension(492, 22));
        InputDNI.add(valueDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 460, -1));

        Content.add(InputDNI);

        jPanel1.setPreferredSize(new java.awt.Dimension(492, 65));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        InputNombre.setBackground(new java.awt.Color(38, 38, 38));
        InputNombre.setPreferredSize(new java.awt.Dimension(492, 65));
        InputNombre.setRoundBottomLeft(6);
        InputNombre.setRoundBottomRight(6);
        InputNombre.setRoundTopLeft(6);
        InputNombre.setRoundTopRight(6);
        InputNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(197, 205, 216));
        jLabel8.setText("Nombres");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        InputNombre.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        valueNombres.setBackground(new java.awt.Color(38, 38, 38));
        valueNombres.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueNombres.setForeground(new java.awt.Color(255, 255, 255));
        valueNombres.setText("...");
        valueNombres.setBorder(null);
        valueNombres.setPreferredSize(new java.awt.Dimension(492, 22));
        InputNombre.add(valueNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 210, -1));

        jPanel1.add(InputNombre);

        InputApellidos.setBackground(new java.awt.Color(38, 38, 38));
        InputApellidos.setPreferredSize(new java.awt.Dimension(492, 65));
        InputApellidos.setRoundBottomLeft(6);
        InputApellidos.setRoundBottomRight(6);
        InputApellidos.setRoundTopLeft(6);
        InputApellidos.setRoundTopRight(6);
        InputApellidos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(197, 205, 216));
        jLabel7.setText("Apellidos");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        InputApellidos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        valueApellidos.setBackground(new java.awt.Color(38, 38, 38));
        valueApellidos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueApellidos.setForeground(new java.awt.Color(255, 255, 255));
        valueApellidos.setText("...");
        valueApellidos.setBorder(null);
        valueApellidos.setPreferredSize(new java.awt.Dimension(492, 22));
        InputApellidos.add(valueApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 210, -1));

        jPanel1.add(InputApellidos);

        Content.add(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(492, 65));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        InputEdad.setBackground(new java.awt.Color(38, 38, 38));
        InputEdad.setPreferredSize(new java.awt.Dimension(492, 65));
        InputEdad.setRoundBottomLeft(6);
        InputEdad.setRoundBottomRight(6);
        InputEdad.setRoundTopLeft(6);
        InputEdad.setRoundTopRight(6);
        InputEdad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(197, 205, 216));
        jLabel9.setText("Edad");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        InputEdad.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        valueEdad.setBackground(new java.awt.Color(38, 38, 38));
        valueEdad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueEdad.setForeground(new java.awt.Color(255, 255, 255));
        valueEdad.setText("...");
        valueEdad.setBorder(null);
        valueEdad.setPreferredSize(new java.awt.Dimension(492, 22));
        InputEdad.add(valueEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 210, -1));

        jPanel2.add(InputEdad);

        InputProcedencia.setBackground(new java.awt.Color(38, 38, 38));
        InputProcedencia.setPreferredSize(new java.awt.Dimension(492, 65));
        InputProcedencia.setRoundBottomLeft(6);
        InputProcedencia.setRoundBottomRight(6);
        InputProcedencia.setRoundTopLeft(6);
        InputProcedencia.setRoundTopRight(6);
        InputProcedencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(197, 205, 216));
        jLabel10.setText("Procedencia");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        InputProcedencia.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        valueProcedencia.setBackground(new java.awt.Color(38, 38, 38));
        valueProcedencia.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueProcedencia.setForeground(new java.awt.Color(255, 255, 255));
        valueProcedencia.setText("...");
        valueProcedencia.setBorder(null);
        valueProcedencia.setPreferredSize(new java.awt.Dimension(492, 22));
        InputProcedencia.add(valueProcedencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 210, -1));

        jPanel2.add(InputProcedencia);

        Content.add(jPanel2);

        InputCorreo.setBackground(new java.awt.Color(38, 38, 38));
        InputCorreo.setPreferredSize(new java.awt.Dimension(492, 65));
        InputCorreo.setRoundBottomLeft(6);
        InputCorreo.setRoundBottomRight(6);
        InputCorreo.setRoundTopLeft(6);
        InputCorreo.setRoundTopRight(6);
        InputCorreo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(197, 205, 216));
        jLabel6.setText("Correo");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        InputCorreo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));

        valueCorreo.setBackground(new java.awt.Color(38, 38, 38));
        valueCorreo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        valueCorreo.setForeground(new java.awt.Color(255, 255, 255));
        valueCorreo.setText("...");
        valueCorreo.setBorder(null);
        valueCorreo.setPreferredSize(new java.awt.Dimension(492, 22));
        InputCorreo.add(valueCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 30, 460, -1));

        Content.add(InputCorreo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stepper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Stepper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DisenoDePatrones.Vista.Components.PanelRound BarProgress;
    private DisenoDePatrones.Vista.Components.PanelRound BarProgress1;
    private javax.swing.JPanel Content;
    private DisenoDePatrones.Vista.Components.PanelRound InputApellidos;
    private DisenoDePatrones.Vista.Components.PanelRound InputCorreo;
    private DisenoDePatrones.Vista.Components.PanelRound InputDNI;
    private DisenoDePatrones.Vista.Components.PanelRound InputEdad;
    private DisenoDePatrones.Vista.Components.PanelRound InputNombre;
    private DisenoDePatrones.Vista.Components.PanelRound InputProcedencia;
    private javax.swing.JPanel Stepper;
    private DisenoDePatrones.Vista.Components.PanelRound decor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameDNI;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound1;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound2;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound3;
    private javax.swing.JTextField valueApellidos;
    private javax.swing.JTextField valueCorreo;
    private javax.swing.JTextField valueDNI;
    private javax.swing.JTextField valueEdad;
    private javax.swing.JTextField valueNombres;
    private javax.swing.JTextField valueProcedencia;
    // End of variables declaration//GEN-END:variables
}
