/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DisenoDePatrones.Vista.Layouts;

import java.awt.Color;

/**
 *
 * @author Alex
 */
public class ReportStep3 extends javax.swing.JPanel {

    /**
     * Creates new form ReportStep1
     */
    public ReportStep3() {
        initComponents();
        Color transparent = new Color(0, 0, 0, 0);
        
        this.setBackground(transparent);
        this.Stepper.setBackground(transparent);
        this.Content.setBackground(transparent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Stepper = new javax.swing.JPanel();
        panelRound2 = new DisenoDePatrones.Vista.Components.PanelRound();
        Step1Label = new javax.swing.JLabel();
        BarProgress = new DisenoDePatrones.Vista.Components.PanelRound();
        decor = new DisenoDePatrones.Vista.Components.PanelRound();
        panelRound3 = new DisenoDePatrones.Vista.Components.PanelRound();
        Step1Label1 = new javax.swing.JLabel();
        BarProgress1 = new DisenoDePatrones.Vista.Components.PanelRound();
        decor1 = new DisenoDePatrones.Vista.Components.PanelRound();
        panelRound1 = new DisenoDePatrones.Vista.Components.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        Stepper.setOpaque(false);
        Stepper.setPreferredSize(new java.awt.Dimension(800, 80));
        Stepper.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        panelRound2.setBackground(new java.awt.Color(38, 38, 38));
        panelRound2.setPreferredSize(new java.awt.Dimension(40, 40));
        panelRound2.setRoundBottomLeft(40);
        panelRound2.setRoundBottomRight(40);
        panelRound2.setRoundTopLeft(40);
        panelRound2.setRoundTopRight(40);
        panelRound2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 8));

        Step1Label.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Step1Label.setForeground(new java.awt.Color(255, 255, 255));
        Step1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/check.png"))); // NOI18N
        panelRound2.add(Step1Label);

        Stepper.add(panelRound2);

        BarProgress.setBackground(new java.awt.Color(197, 205, 216));
        BarProgress.setPreferredSize(new java.awt.Dimension(205, 6));
        BarProgress.setRoundBottomLeft(6);
        BarProgress.setRoundBottomRight(6);
        BarProgress.setRoundTopLeft(6);
        BarProgress.setRoundTopRight(6);
        BarProgress.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decor.setBackground(new java.awt.Color(38, 38, 38));
        decor.setPreferredSize(new java.awt.Dimension(205, 6));
        decor.setRoundBottomLeft(6);
        decor.setRoundBottomRight(6);
        decor.setRoundTopLeft(6);
        decor.setRoundTopRight(6);

        javax.swing.GroupLayout decorLayout = new javax.swing.GroupLayout(decor);
        decor.setLayout(decorLayout);
        decorLayout.setHorizontalGroup(
            decorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        decorLayout.setVerticalGroup(
            decorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        BarProgress.add(decor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Stepper.add(BarProgress);

        panelRound3.setBackground(new java.awt.Color(38, 38, 38));
        panelRound3.setPreferredSize(new java.awt.Dimension(40, 40));
        panelRound3.setRoundBottomLeft(40);
        panelRound3.setRoundBottomRight(40);
        panelRound3.setRoundTopLeft(40);
        panelRound3.setRoundTopRight(40);
        panelRound3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 8));

        Step1Label1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Step1Label1.setForeground(new java.awt.Color(255, 255, 255));
        Step1Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DisenoDePatrones/Vista/Assets/check.png"))); // NOI18N
        panelRound3.add(Step1Label1);

        Stepper.add(panelRound3);

        BarProgress1.setBackground(new java.awt.Color(197, 205, 216));
        BarProgress1.setPreferredSize(new java.awt.Dimension(205, 6));
        BarProgress1.setRoundBottomLeft(6);
        BarProgress1.setRoundBottomRight(6);
        BarProgress1.setRoundTopLeft(6);
        BarProgress1.setRoundTopRight(6);
        BarProgress1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decor1.setBackground(new java.awt.Color(38, 38, 38));
        decor1.setPreferredSize(new java.awt.Dimension(205, 6));
        decor1.setRoundBottomLeft(6);
        decor1.setRoundBottomRight(6);
        decor1.setRoundTopLeft(6);
        decor1.setRoundTopRight(6);

        javax.swing.GroupLayout decor1Layout = new javax.swing.GroupLayout(decor1);
        decor1.setLayout(decor1Layout);
        decor1Layout.setHorizontalGroup(
            decor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        decor1Layout.setVerticalGroup(
            decor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        BarProgress1.add(decor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Stepper.add(BarProgress1);

        panelRound1.setBackground(new java.awt.Color(38, 38, 38));
        panelRound1.setPreferredSize(new java.awt.Dimension(160, 40));
        panelRound1.setRoundBottomLeft(40);
        panelRound1.setRoundBottomRight(40);
        panelRound1.setRoundTopLeft(40);
        panelRound1.setRoundTopRight(40);
        panelRound1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 2));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("3");
        panelRound1.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Completado");
        panelRound1.add(jLabel1);

        Stepper.add(panelRound1);

        Content.setOpaque(false);
        Content.setPreferredSize(new java.awt.Dimension(800, 80));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(38, 38, 38));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("COMPLETADO");
        Content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 260, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 38, 38));
        jLabel4.setText("solicitud y/o reporte lo mas pronto posible");
        Content.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(38, 38, 38));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("REPORTE Y/O SOLICITUD");
        Content.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 400, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(38, 38, 38));
        jLabel6.setText("Gracias por su colaboración");
        Content.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(38, 38, 38));
        jLabel7.setText("Estamos trabajando muy rápido, para proceder con su respectiva");
        Content.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stepper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Stepper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private DisenoDePatrones.Vista.Components.PanelRound BarProgress;
    private DisenoDePatrones.Vista.Components.PanelRound BarProgress1;
    private javax.swing.JPanel Content;
    private javax.swing.JLabel Step1Label;
    private javax.swing.JLabel Step1Label1;
    private javax.swing.JPanel Stepper;
    private DisenoDePatrones.Vista.Components.PanelRound decor;
    private DisenoDePatrones.Vista.Components.PanelRound decor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound1;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound2;
    private DisenoDePatrones.Vista.Components.PanelRound panelRound3;
    // End of variables declaration//GEN-END:variables
}
